# Form implementation generated from reading ui file '/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/Concept_Portrait.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 737))
        MainWindow.setStyleSheet(" background-color: #f5efe8;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("QPushButton#pushButtonBack {\n"
"    background-color: transparent;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton#pushButtonBack:hover {\n"
"    background-color: #E8D8C4;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../../contact/images/left_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_3.addWidget(self.pushButtonBack)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(240, 300))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(
            "/guest_ui/guest_gallery/images/Portrait/613705475_17984731358930408_5059974921820876885_n.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(220, 300))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(
            "/guest_ui/guest_gallery/images/Portrait/641534800_17988921755930408_7753007074676520363_n.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(220, 300))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(
            "/guest_ui/guest_gallery/images/Portrait/638313366_17989136837930408_7086427777565813361_n.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(220, 300))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "/guest_ui/guest_gallery/images/Portrait/625020464_17986243661930408_4203013993903022732_n.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(220, 300))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(
            "/guest_ui/guest_gallery/images/Portrait/630024908_17987933759930408_7914660855801865906_n.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(200, 300))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(
            "/guest_ui/guest_gallery/images/Portrait/487414056_635042436183746_6697205309929125131_n.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBack.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Back</span></p></body></html>"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
