# Form implementation generated from reading ui file '/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/GuestGalleryMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 770)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 770))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 770))
        MainWindow.setSizeIncrement(QtCore.QSize(1000, 0))
        MainWindow.setStyleSheet("/* ===== GLOBAL FONT ===== */\n"
"* {\n"
"    font-family: \"Playfair Display\";\n"
"}\n"
"\n"
"/* ===== PAGE BACKGROUND ===== */\n"
"QMainWindow {\n"
"    background-color: #F5EBDD;\n"
"}\n"
"\n"
"/* ===== GALLERY TITLE ===== */\n"
"#galleryTitle {\n"
"    color: #6B3F2A;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    \n"
"}\n"
"\n"
"/* ===== GALLERY FRAME (KHUNG NGOÀI) ===== */\n"
"#galleryFrame {\n"
"    background-color: #F8F1E8;\n"
"    border: 2px solid #C28B5D;    /* nâu caramel */\n"
"    border-radius: 22px;          /* bo góc ngoài */\n"
"    padding: 20px;\n"
"}\n"
"\n"
"/* ===== IMAGE BOXES — VUÔNG, KHÔNG BO GÓC ===== */\n"
"#img_1, \n"
"#img_2, \n"
"#img_3, \n"
"#img_4, \n"
"#img_5, \n"
"#img_6, \n"
"#img_7, \n"
"#img_8, \n"
"#img_9 {\n"
"    background-color: #FFF9F3;\n"
"    border: 2px solid #C28B5D;   /* màu nâu giống mẫu */\n"
"    border-radius: 0px;          /* VUÔNG hoàn toàn */\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* ===== VIEW MORE BUTTON ===== */\n"
"#viewMoreButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #B8845E;\n"
"    border-radius: 24px;\n"
"    padding: 10px 35px;\n"
"    font-size: 18px;\n"
"    border: none;\n"
"}\n"
"\n"
"#viewMoreButton:hover {\n"
"    background-color: #A6734D;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1060, 0, 131, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../../guest_booking/images/Subject 2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, -20, 251, 111))
        self.label_2.setStyleSheet("QLabel#label_2 {\n"
"    color: #6e4c35;\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 38px;\n"
"    font-weight: 600;\n"
"    background-color:transparent;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.labelBirthday = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBirthday.setGeometry(QtCore.QRect(230, 70, 251, 331))
        self.labelBirthday.setMaximumSize(QtCore.QSize(5555555, 16777215))
        self.labelBirthday.setText("")
        self.labelBirthday.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../images/z7605046228493_b2502f01ab46685710a569ecda6b2745.png"))
        self.labelBirthday.setScaledContents(True)
        self.labelBirthday.setObjectName("labelBirthday")
        self.labelPortrait = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPortrait.setGeometry(QtCore.QRect(540, 70, 251, 331))
        self.labelPortrait.setMaximumSize(QtCore.QSize(55555, 55555))
        self.labelPortrait.setText("")
        self.labelPortrait.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../images/z7605046228573_f50c8f856f4df3addf716125ad51f183.png"))
        self.labelPortrait.setScaledContents(True)
        self.labelPortrait.setObjectName("labelPortrait")
        self.labelGeneration = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelGeneration.setGeometry(QtCore.QRect(150, 430, 211, 271))
        self.labelGeneration.setMaximumSize(QtCore.QSize(44455, 544444))
        self.labelGeneration.setText("")
        self.labelGeneration.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../images/z7605046108556_93759be82836558ea65f0fcb8a31af4b.png"))
        self.labelGeneration.setScaledContents(True)
        self.labelGeneration.setObjectName("labelGeneration")
        self.labelPreWedding = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPreWedding.setGeometry(QtCore.QRect(400, 430, 211, 271))
        self.labelPreWedding.setMaximumSize(QtCore.QSize(55555, 555555))
        self.labelPreWedding.setText("")
        self.labelPreWedding.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../images/z7605046184771_48c2eda2fa3f9692a5f37787d3114db2.png"))
        self.labelPreWedding.setScaledContents(True)
        self.labelPreWedding.setObjectName("labelPreWedding")
        self.labelProfile = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelProfile.setGeometry(QtCore.QRect(650, 430, 201, 271))
        self.labelProfile.setMaximumSize(QtCore.QSize(544444, 5444444))
        self.labelProfile.setText("")
        self.labelProfile.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../images/z7605046126575_8d54da41a26d0c3c3f12305c138c537e.png"))
        self.labelProfile.setScaledContents(True)
        self.labelProfile.setObjectName("labelProfile")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(40, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Playfair Display")
        font.setBold(True)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("QPushButton#pushButtonBack {\n"
"    background-color: transparent;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton#pushButtonBack:hover {\n"
"    background-color: #E8D8C4;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/guest_gallery/ui/../../contact/images/left_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:38pt;\">Gallery</span></p></body></html>"))
        self.pushButtonBack.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Back</p></body></html>"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
