# Form implementation generated from reading ui file '/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/managing_booking/ui/AppointmentMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 730)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 730))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 730))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #fbf5e9;\n"
"    font-family: \"Inter\";\n"
"    color: #3a2e24;\n"
"}\n"
"\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(370, 10, 450, 50))
        self.lbl_title.setMinimumSize(QtCore.QSize(450, 50))
        self.lbl_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbl_title.setStyleSheet("QLabel {\n"
"    background-color: #b08968;\n"
"    border-radius: 14px;\n"
"    color: #ffffff;\n"
"font-family: \"Playfair Display\";\n"
"    font-size: 30px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0px;\n"
"}")
        self.lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 70, 1200, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1200, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
" border-radius: 10px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #ebd6c1;\n"
"    color: #3a2e24;\n"
"    padding: 8px 18px;\n"
"    border-radius: 10px;\n"
"    margin-right: 6px;\n"
"    font-weight: 500;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #b08968;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_lich_hen = QtWidgets.QWidget()
        self.tab_lich_hen.setObjectName("tab_lich_hen")
        self.vbox_tab1 = QtWidgets.QVBoxLayout(self.tab_lich_hen)
        self.vbox_tab1.setObjectName("vbox_tab1")
        self.layout_toolbar = QtWidgets.QHBoxLayout()
        self.layout_toolbar.setObjectName("layout_toolbar")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.tab_lich_hen)
        self.pushButtonAdd.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #d8cfc4;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #7b6046;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"")
        self.pushButtonAdd.setCheckable(True)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.layout_toolbar.addWidget(self.pushButtonAdd)
        self.pushButtonClearFilters = QtWidgets.QPushButton(parent=self.tab_lich_hen)
        self.pushButtonClearFilters.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #d8cfc4;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #7b6046;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"")
        self.pushButtonClearFilters.setCheckable(True)
        self.pushButtonClearFilters.setObjectName("pushButtonClearFilters")
        self.layout_toolbar.addWidget(self.pushButtonClearFilters)
        self.pushButtonConfirmed = QtWidgets.QPushButton(parent=self.tab_lich_hen)
        self.pushButtonConfirmed.setStyleSheet("QPushButton {\n"
"    background-color: #E6F4EA;       \n"
"    color: #2E7D32;                   \n"
"    border: 1px solid #81C784;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C8E6C9;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.pushButtonConfirmed.setCheckable(True)
        self.pushButtonConfirmed.setObjectName("pushButtonConfirmed")
        self.layout_toolbar.addWidget(self.pushButtonConfirmed)
        self.pushButtonPending = QtWidgets.QPushButton(parent=self.tab_lich_hen)
        self.pushButtonPending.setStyleSheet("QPushButton {\n"
"    background-color: #FDECEA;       \n"
"    color: #C62828;                 \n"
"    border: 1px solid #EF9A9A;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F9D6D3;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #E53935;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.pushButtonPending.setCheckable(True)
        self.pushButtonPending.setObjectName("pushButtonPending")
        self.layout_toolbar.addWidget(self.pushButtonPending)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.tab_lich_hen)
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: #fdf8f3;\n"
"    border: 2px solid #d8cfc4;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QDateEdit:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.layout_toolbar.addWidget(self.dateEdit)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_toolbar.addItem(spacerItem)
        self.search_box = QtWidgets.QLineEdit(parent=self.tab_lich_hen)
        self.search_box.setStyleSheet("QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d8cfc4;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #7b6046;\n"
"}\n"
"")
        self.search_box.setObjectName("search_box")
        self.layout_toolbar.addWidget(self.search_box)
        self.vbox_tab1.addLayout(self.layout_toolbar)
        self.tableWidgetBooking = QtWidgets.QTableWidget(parent=self.tab_lich_hen)
        self.tableWidgetBooking.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"\n"
"")
        self.tableWidgetBooking.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.tableWidgetBooking.setObjectName("tableWidgetBooking")
        self.tableWidgetBooking.setColumnCount(10)
        self.tableWidgetBooking.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(9, item)
        self.vbox_tab1.addWidget(self.tableWidgetBooking)
        self.tabWidget.addTab(self.tab_lich_hen, "")
        self.frame_form_left_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_form_left_2.setGeometry(QtCore.QRect(840, 430, 341, 161))
        self.frame_form_left_2.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"")
        self.frame_form_left_2.setObjectName("frame_form_left_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_form_left_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_form_left_2)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.radioButtonConfirmed = QtWidgets.QRadioButton(parent=self.frame_form_left_2)
        self.radioButtonConfirmed.setStyleSheet("QRadioButton {\n"
"    background-color: #E6F4EA;       \n"
"    color: #2E7D32;                   \n"
"    border: 1px solid #81C784;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    background-color: #C8E6C9;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"")
        self.radioButtonConfirmed.setObjectName("radioButtonConfirmed")
        self.verticalLayout.addWidget(self.radioButtonConfirmed)
        self.radioButtonPending = QtWidgets.QRadioButton(parent=self.frame_form_left_2)
        self.radioButtonPending.setStyleSheet("QRadioButton {\n"
"    background-color: #FFF3E0;       \n"
"    color: #E65100;                 \n"
"    border: 1px solid #FFCC80;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"    font-family: \"Inter\";\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    background-color: #FFE0B2;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    background-color: #FB8C00;\n"
"    color: white;\n"
"    border: none;\n"
"}")
        self.radioButtonPending.setObjectName("radioButtonPending")
        self.verticalLayout.addWidget(self.radioButtonPending)
        self.radioButtonCancel = QtWidgets.QRadioButton(parent=self.frame_form_left_2)
        self.radioButtonCancel.setStyleSheet("QRadioButton {\n"
"    background-color: #FDECEA;       \n"
"    color: #C62828;                 \n"
"    border: 1px solid #EF9A9A;\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    background-color: #F9D6D3;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    background-color: #E53935;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.radioButtonCancel.setObjectName("radioButtonCancel")
        self.verticalLayout.addWidget(self.radioButtonCancel)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.frame_form_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_form_left.setGeometry(QtCore.QRect(10, 370, 821, 341))
        self.frame_form_left.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"")
        self.frame_form_left.setObjectName("frame_form_left")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_form_left)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_2.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_5.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 1, 1, 1, 1)
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.gridLayout.addWidget(self.lineEditPhone, 3, 1, 1, 1)
        self.lineEditLocation = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditLocation.setObjectName("lineEditLocation")
        self.gridLayout.addWidget(self.lineEditLocation, 7, 1, 1, 1)
        self.lineEditDate = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditDate.setObjectName("lineEditDate")
        self.gridLayout.addWidget(self.lineEditDate, 5, 1, 1, 1)
        self.lineEditTime = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditTime.setObjectName("lineEditTime")
        self.gridLayout.addWidget(self.lineEditTime, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_form_left)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 2)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_4.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_form_left)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 2)
        self.label1 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label1.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_3.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_19.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEditPackage = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditPackage.setObjectName("lineEditPackage")
        self.gridLayout_2.addWidget(self.lineEditPackage, 1, 1, 1, 1)
        self.lineEditPromo = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditPromo.setObjectName("lineEditPromo")
        self.gridLayout_2.addWidget(self.lineEditPromo, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 2)
        self.lineEditConcept = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditConcept.setObjectName("lineEditConcept")
        self.gridLayout_2.addWidget(self.lineEditConcept, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_20.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_21.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEditNote = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditNote.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditNote.setMaximumSize(QtCore.QSize(16777215, 90))
        self.lineEditNote.setSizeIncrement(QtCore.QSize(0, 50))
        self.lineEditNote.setObjectName("lineEditNote")
        self.gridLayout_4.addWidget(self.lineEditNote, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_25.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_17.setMinimumSize(QtCore.QSize(0, 50))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_17.setSizeIncrement(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(0, 20, 93, 28))
        self.pushButtonBack.setStyleSheet("background-color: transparent;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/managing_booking/ui/../../../guest_ui/contact/images/left_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(840, 380, 331, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #e74c3c;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 18px;\n"
"    font-weight: 600;\n"
" font-size: 15px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #c0392b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #922b21;\n"
"}\n"
"")
        self.pushButtonCancel.setCheckable(True)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonConfirm.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 18px;\n"
"    font-weight: 600;\n"
" font-size: 15px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"}\n"
"")
        self.pushButtonConfirm.setCheckable(True)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout.addWidget(self.pushButtonConfirm)
        self.pushButtonEdit = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonEdit.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 18px;\n"
"    font-weight: 600;\n"
" font-size: 15px;\n"
"font-family: \"Inter\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2e86c1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #21618c;\n"
"}\n"
"")
        self.pushButtonEdit.setCheckable(True)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout.addWidget(self.pushButtonEdit)
        self.lbl_title.raise_()
        self.tabWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButtonBack.raise_()
        self.frame_form_left.raise_()
        self.frame_form_left_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản Lý Lịch Hẹn - Admin"))
        self.lbl_title.setText(_translate("MainWindow", "Appointment Management "))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add Appointment"))
        self.pushButtonClearFilters.setText(_translate("MainWindow", "Clear Filters"))
        self.pushButtonConfirmed.setText(_translate("MainWindow", "Confirmed"))
        self.pushButtonPending.setText(_translate("MainWindow", "Pending"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.search_box.setPlaceholderText(_translate("MainWindow", "Search…"))
        item = self.tableWidgetBooking.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetBooking.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetBooking.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidgetBooking.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidgetBooking.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidgetBooking.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Package"))
        item = self.tableWidgetBooking.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Concept"))
        item = self.tableWidgetBooking.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Location"))
        item = self.tableWidgetBooking.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidgetBooking.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Created At"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lich_hen), _translate("MainWindow", "    List of Appoinments    "))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">STATUS</span></p></body></html>"))
        self.radioButtonConfirmed.setText(_translate("MainWindow", "Confirmed"))
        self.radioButtonPending.setText(_translate("MainWindow", "Pending"))
        self.radioButtonCancel.setText(_translate("MainWindow", "Cancel"))
        self.label_2.setText(_translate("MainWindow", "Date:"))
        self.label.setText(_translate("MainWindow", "Phone number:"))
        self.label_5.setText(_translate("MainWindow", "Email:"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">SHOOTING TIME</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Location:"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">CUSTOMER DETAILS</span></p></body></html>"))
        self.label1.setText(_translate("MainWindow", "Customer:"))
        self.label_3.setText(_translate("MainWindow", "Time:"))
        self.label_19.setText(_translate("MainWindow", "Package:"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">SERVICE </span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Concept:"))
        self.label_21.setText(_translate("MainWindow", "Promo:"))
        self.label_25.setText(_translate("MainWindow", "Note:"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">NOTE</span></p></body></html>"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButtonConfirm.setText(_translate("MainWindow", "Confirm "))
        self.pushButtonEdit.setText(_translate("MainWindow", "Update"))
