# Form implementation generated from reading ui file 'E:\Elearning\K25411E\Do_an\Home\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1200, 720)
        Home.setMinimumSize(QtCore.QSize(1200, 720))
        self.centralwidget = QtWidgets.QWidget(parent=Home)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1200, 720))
        self.label.setMinimumSize(QtCore.QSize(1200, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/ACER/OneDrive/Pictures/Beige and Brown Minimalist Modern Business Presentation.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.brandTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.brandTitle.setGeometry(QtCore.QRect(90, 140, 381, 141))
        self.brandTitle.setStyleSheet("QLabel {\n"
"font-family: \"Allura\";\n"
"font-size: 80px;\n"
"font-weight: normal; \n"
"color: #fbf5e9;\n"
"}\n"
"")
        self.brandTitle.setObjectName("brandTitle")
        self.btnBooking = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBooking.setGeometry(QtCore.QRect(90, 360, 151, 51))
        self.btnBooking.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Inter\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"\n"
"")
        self.btnBooking.setObjectName("btnBooking")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(270, 360, 151, 51))
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Inter\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 250, 511, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 28px;\n"
"    font-weight: 600;\n"
"    color: #fbf5e9;\n"
"   letter-spacing: 1px;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/ACER/OneDrive/Pictures/logo2.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 550, 441, 41))
        self.label_3.setStyleSheet("\n"
"color: rgb(123, 96, 70);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 460, 461, 31))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: \"Playfair Display\";\n"
"    color: #fbf5e9;\n"
"    font-size: 15px;\n"
"    font-style: italic;\n"
"    letter-spacing: 1px;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 30, 432, 45))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnHome = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnHome.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
" font-family: \"Inter\";\n"
"    color: #7b6046;\n"
"    font-size: 16px;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #4e3b2a;\n"
"    border-bottom: 2px solid #7b6046;\n"
"}\n"
"QPushButton {\n"
" \n"
"    font-weight: 600;\n"
"    padding: 10px 18px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.btnHome.setObjectName("btnHome")
        self.horizontalLayout.addWidget(self.btnHome)
        self.btnGallery = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnGallery.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
" font-family: \"Inter\";\n"
"    color: #7b6046;\n"
"    font-size: 16px;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #4e3b2a;\n"
"    border-bottom: 2px solid #7b6046;\n"
"}\n"
"QPushButton {\n"
" \n"
"    font-weight: 600;\n"
"    padding: 10px 18px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.btnGallery.setObjectName("btnGallery")
        self.horizontalLayout.addWidget(self.btnGallery)
        self.btnGallery_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnGallery_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
" font-family: \"Inter\";\n"
"    color: #7b6046;\n"
"    font-size: 16px;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #4e3b2a;\n"
"    border-bottom: 2px solid #7b6046;\n"
"}\n"
"QPushButton {\n"
" \n"
"    font-weight: 600;\n"
"    padding: 10px 18px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.btnGallery_2.setObjectName("btnGallery_2")
        self.horizontalLayout.addWidget(self.btnGallery_2)
        self.btnContact = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnContact.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
" font-family: \"Inter\";\n"
"    color: #7b6046;\n"
"    font-size: 16px;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #4e3b2a;\n"
"    border-bottom: 2px solid #7b6046;\n"
"}\n"
"QPushButton {\n"
" \n"
"    font-weight: 600;\n"
"    padding: 10px 18px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.btnContact.setObjectName("btnContact")
        self.horizontalLayout.addWidget(self.btnContact)
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.brandTitle.setText(_translate("Home", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">LUMORA</span></p></body></html>"))
        self.btnBooking.setText(_translate("Home", "BOOKING"))
        self.btnLogin.setText(_translate("Home", "LOGIN"))
        self.label_2.setText(_translate("Home", "- Professional photography studio -"))
        self.label_3.setText(_translate("Home", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">──────────── ✧ ✦ ✧ ────────────</span></p></body></html>"))
        self.label_5.setText(_translate("Home", "“Book the Light, Capture the Moment”"))
        self.btnHome.setText(_translate("Home", "HOME"))
        self.btnGallery.setText(_translate("Home", "GALLERY"))
        self.btnGallery_2.setText(_translate("Home", "REVIEW"))
        self.btnContact.setText(_translate("Home", "CONTACT"))
