# Form implementation generated from reading ui file '/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #fbf5e9;\n"
"}\n"
"QLineEdit, QComboBox, QDateEdit, QTimeEdit{\n"
"    background: rgba(255,255,255,170);\n"
"    border: 1px solid rgba(155,115,84,120);\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    color: #6b4b38;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QDateEdit:focus, QTimeEdit:focus{\n"
"    border: 2px solid #9b7354;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f6efe8;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QLineEdit, QComboBox, QDateEdit, QTimeEdit{\n"
"    background: rgba(255,255,255,170);\n"
"    border: 1px solid rgba(155,115,84,120);\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    color: #6b4b38;\n"
"}\n"
"QLineEdit:focus, QComboBox:focus, QDateEdit:focus, QTimeEdit:focus{\n"
"    border: 2px solid #9b7354;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frameHeader = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameHeader.setGeometry(QtCore.QRect(0, 20, 1200, 41))
        self.frameHeader.setMinimumSize(QtCore.QSize(0, 0))
        self.frameHeader.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameHeader.setStyleSheet("QFrame#frameHeader {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #a67c52,\n"
"        stop:1 #8c6445\n"
"    );\n"
"    border: none;\n"
"}\n"
"QFrame#frameHeader {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #b8926f,\n"
"        stop:1 #9c7356\n"
"    );\n"
"    border-bottom: 2px solid #7b573c;\n"
"}\n"
"Font size: 20\n"
"Letter spacing: 2px\n"
"Font-weight: 600")
        self.frameHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.label = QtWidgets.QLabel(parent=self.frameHeader)
        self.label.setGeometry(QtCore.QRect(170, 10, 181, 31))
        self.label.setStyleSheet("background: transparent;\n"
"font: 13pt \"Playfair Display\";\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;\n"
"")
        self.label.setObjectName("label")
        self.framePhoneBox = QtWidgets.QFrame(parent=self.frameHeader)
        self.framePhoneBox.setGeometry(QtCore.QRect(830, 0, 261, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePhoneBox.sizePolicy().hasHeightForWidth())
        self.framePhoneBox.setSizePolicy(sizePolicy)
        self.framePhoneBox.setStyleSheet("QFrame {\n"
"    background-color: #ead7c8;\n"
"    border: 2px solid #b58a6a;\n"
"    border-radius: 25px;\n"
"}")
        self.framePhoneBox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.framePhoneBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.framePhoneBox.setObjectName("framePhoneBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.framePhoneBox)
        self.horizontalLayout.setContentsMargins(8, 8, 6, 6)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPhone = QtWidgets.QPushButton(parent=self.framePhoneBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPhone.sizePolicy().hasHeightForWidth())
        self.btnPhone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnPhone.setFont(font)
        self.btnPhone.setStyleSheet("QPushButton#btnPhone {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #7a5235;\n"
"    font: 16pt ;\n"
"    font-weight: 600;\n"
"    padding-left: 40px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QPushButton#btnPhone:hover {\n"
"    color: #9b7354;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/../../../Downloads/ChatGPT Image Feb 13, 2026, 09_46_10 AM.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPhone.setIcon(icon)
        self.btnPhone.setIconSize(QtCore.QSize(70, 120))
        self.btnPhone.setObjectName("btnPhone")
        self.horizontalLayout.addWidget(self.btnPhone)
        self.frameCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameCard.setGeometry(QtCore.QRect(80, 190, 1041, 400))
        self.frameCard.setMaximumSize(QtCore.QSize(1200, 550))
        self.frameCard.setStyleSheet("QFrame#frameCard {\n"
"    background-color: #f2e4d8;\n"
"    border: 2px solid #b28766;\n"
"    border-radius: 20px;\n"
"}")
        self.frameCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCard.setObjectName("frameCard")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frameCard)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 50, 281, 36))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #a67c5b;   /* chỉnh màu placeholder đậm hơn */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frameCard)
        self.lineEdit_4.setGeometry(QtCore.QRect(350, 50, 271, 36))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #a67c5b;   /* chỉnh màu placeholder đậm hơn */\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_3.setGeometry(QtCore.QRect(480, 180, 151, 21))
        self.label_3.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.frameCard)
        self.comboBox.setGeometry(QtCore.QRect(30, 210, 191, 36))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #F5EFE7;\n"
"    border: 2px solid #B07A4F;\n"
"    border-radius: 18px;\n"
"    padding: 6px 35px 6px 15px;\n"
"    color: #6B4C3B;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #B07A4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(/Users/hanhnguyen/Documents/icons/arrow_down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_9.setGeometry(QtCore.QRect(30, 260, 151, 16))
        self.label_9.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.btnBook = QtWidgets.QPushButton(parent=self.frameCard)
        self.btnBook.setGeometry(QtCore.QRect(380, 340, 231, 51))
        self.btnBook.setStyleSheet("QPushButton {\n"
"    background-color: #b67842;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font: bold 17px \"Playfair Display\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #9b6032;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/../../../Downloads/ChatGPT Image 10_40_48 10 thg 3, 2026.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBook.setIcon(icon1)
        self.btnBook.setIconSize(QtCore.QSize(60, 60))
        self.btnBook.setObjectName("btnBook")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.frameCard)
        self.timeEdit.setGeometry(QtCore.QRect(520, 120, 161, 41))
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frameCard)
        self.textEdit.setGeometry(QtCore.QRect(30, 280, 601, 51))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #f5f0ea;\n"
"    border: 1.5px solid #c9a98d;\n"
"    border-radius: 18px;\n"
"    padding: 10px 15px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #7a5a44;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #b67842;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.frameCard)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 210, 171, 36))
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    background-color: #F5EFE7;\n"
"    border: 2px solid #B07A4F;\n"
"    border-radius: 18px;\n"
"    padding: 6px 35px 6px 15px;\n"
"    color: #6B4C3B;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #B07A4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(/Users/hanhnguyen/Documents/icons/arrow_down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.frameCard)
        self.comboBox_3.setGeometry(QtCore.QRect(470, 210, 181, 36))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: #F5EFE7;\n"
"    border: 2px solid #B07A4F;\n"
"    border-radius: 18px;\n"
"    padding: 6px 35px 6px 15px;\n"
"    color: #6B4C3B;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #B07A4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(/Users/hanhnguyen/Documents/icons/arrow_down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.comboBox_3.setFrame(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frameCard)
        self.dateEdit.setGeometry(QtCore.QRect(200, 120, 151, 41))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_2.setGeometry(QtCore.QRect(260, 180, 89, 19))
        self.label_2.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_5.setGeometry(QtCore.QRect(350, 20, 101, 21))
        self.label_5.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Playfair Display")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_8.setGeometry(QtCore.QRect(520, 90, 79, 19))
        self.label_8.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_7.setGeometry(QtCore.QRect(200, 90, 101, 21))
        self.label_7.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 135, 19))
        self.label_4.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_11.setGeometry(QtCore.QRect(710, 180, 281, 31))
        self.label_11.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.frameCard)
        self.comboBox_4.setGeometry(QtCore.QRect(700, 210, 271, 41))
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    background-color: #F5EFE7;\n"
"    border: 2px solid #B07A4F;\n"
"    border-radius: 18px;\n"
"    padding: 6px 35px 6px 15px;\n"
"    color: #6B4C3B;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left: 2px solid #B07A4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image:url(/Users/hanhnguyen/Documents/icons/arrow_down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_12 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_12.setGeometry(QtCore.QRect(700, 250, 261, 41))
        self.label_12.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frameCard)
        self.lineEdit.setGeometry(QtCore.QRect(700, 280, 281, 51))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #a67c5b;   /* chỉnh màu placeholder đậm hơn */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_16 = QtWidgets.QLabel(parent=self.frameCard)
        self.label_16.setGeometry(QtCore.QRect(680, 20, 121, 21))
        self.label_16.setStyleSheet("QLabel{\n"
"    font: 18pt \"Playfair Display\";\n"
"  background: transparent;\n"
"  color: rgba(106,75,58,200);\n"
"  font-size: 14px;\n"
"  font-weight: 600;\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frameCard)
        self.lineEdit_5.setGeometry(QtCore.QRect(670, 50, 271, 36))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #a67c5b;   /* chỉnh màu placeholder đậm hơn */\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(210, 90, 721, 41))
        self.labelTitle.setStyleSheet("QLabel#labelTitle {\n"
"    color: #6e4c35;\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 38px;\n"
"    font-weight: 600;\n"
"    background-color:transparent;\n"
"}")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.frameHeader_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameHeader_2.setGeometry(QtCore.QRect(0, 620, 1200, 31))
        self.frameHeader_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frameHeader_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameHeader_2.setStyleSheet("QFrame#frameHeader_2 {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #a67c52,\n"
"        stop:1 #8c6445\n"
"    );\n"
"    border: none;\n"
"}\n"
"QFrame#frameHeader_2 {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #b8926f,\n"
"        stop:1 #9c7356\n"
"    );\n"
"    border-bottom: 2px solid #7b573c;\n"
"}\n"
"Font size: 20\n"
"Letter spacing: 2px\n"
"Font-weight: 600")
        self.frameHeader_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameHeader_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameHeader_2.setObjectName("frameHeader_2")
        self.labelDesc = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelDesc.setGeometry(QtCore.QRect(200, 130, 800, 60))
        self.labelDesc.setStyleSheet("QLabel#labelDesc {\n"
"    color: #8b6b52;\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 16px;\n"
"    background-color:transparent;\n"
"}")
        self.labelDesc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelDesc.setObjectName("labelDesc")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(940, 70, 81, 91))
        self.label_14.setStyleSheet("background-color:transparent\n"
"")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/../../../Downloads/ChatGPT Image Feb 13, 2026, 11_20_27 PM.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.labelLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelLogo.setGeometry(QtCore.QRect(30, -10, 161, 121))
        self.labelLogo.setAutoFillBackground(False)
        self.labelLogo.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font-size: 18px;\n"
"font-weight: 600;\n"
"")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/../../../Downloads/ChatGPT Image Feb 12, 2026, 06_00_15 PM.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 100, 51, 32))
        self.pushButton.setStyleSheet("background-color:transparent")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/../../../Downloads/left-arrow_608286.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(330, 580, 611, 41))
        self.label_15.setStyleSheet("QLabel#label_15 {\n"
"    color: #8b6b52;\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 16px;\n"
"    background-color:transparent;\n"
"}")
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "STUDIO LUMORA"))
        self.btnPhone.setText(_translate("MainWindow", "018 888 888"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter your full name"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Enter your email address"))
        self.label_3.setText(_translate("MainWindow", "Number of People:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select concept"))
        self.label_9.setText(_translate("MainWindow", "Additional Notes:"))
        self.btnBook.setText(_translate("MainWindow", "BOOK NOW"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Enter additional notes (optional)"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select Type"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Select number of people"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_2.setText(_translate("MainWindow", "Session Type:"))
        self.label_5.setText(_translate("MainWindow", "Email Address:"))
        self.label_6.setText(_translate("MainWindow", "Full Name:"))
        self.label_8.setText(_translate("MainWindow", "Shoot Time:"))
        self.label_7.setText(_translate("MainWindow", "Shoot Date:"))
        self.label_4.setText(_translate("MainWindow", "Photoshoot Concept:"))
        self.label_11.setText(_translate("MainWindow", "Choose Your Session Package:"))
        self.label_12.setText(_translate("MainWindow", "Apply Promo Code (Optional):"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter promo code"))
        self.label_16.setText(_translate("MainWindow", "Phone Number:"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Enter your phone number"))
        self.labelTitle.setText(_translate("MainWindow", "ONLINE PHOTOSHOOT BOOKING"))
        self.labelDesc.setText(_translate("MainWindow", "Thank you for trusting and using Studio Lumora’s services!\n"
"Please fill in your information to book a photoshoot appointment, and we will contact you shortly."))
        self.label_15.setText(_translate("MainWindow", "Sincerely thank you for choosing the photo booking service at Lumora Studio!"))
