# Form implementation generated from reading ui file 'E:\Elearning\K25411E\Do_an\Review\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 720))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #f4efe9;\n"
"    font-size: 14px;\n"
"    color: #4a3b2c;\n"
"}\n"
"QFrame#pillFrame {\n"
"    background-color: #ebd6c1;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel#pillText {\n"
"    background-color: transparent;\n"
"    color: #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 0, 571, 41))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 42px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 4px;\n"
"    color: #7b6046;\n"
"  background-color: transparent;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Allura")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 28px;\n"
"font-family: \"Allura\";\n"
"    font-style: italic;\n"
"    font-weight: 600;\n"
"    color: #5a4332;\n"
"    letter-spacing: 5px;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pillFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.pillFrame.setGeometry(QtCore.QRect(90, 90, 341, 41))
        self.pillFrame.setStyleSheet("QFrame#pillFrame {\n"
"    background-color: #ebd6c1;\n"
"      border-radius: 18px;\n"
"    border: 2px solid #8b6b4f;\n"
"    padding: 50px;\n"
"}")
        self.pillFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pillFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pillFrame.setObjectName("pillFrame")
        self.pillText = QtWidgets.QLabel(parent=self.pillFrame)
        self.pillText.setGeometry(QtCore.QRect(60, 0, 141, 41))
        self.pillText.setAccessibleDescription("")
        self.pillText.setAutoFillBackground(False)
        self.pillText.setStyleSheet("  background-color: transparent;\n"
"    font-size: 25px;\n"
"    font-weight: 700;\n"
"    color: #7b6046;\n"
"    font-family: \"Inter\";\n"
"")
        self.pillText.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pillText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pillText.setObjectName("pillText")
        self.label_5 = QtWidgets.QLabel(parent=self.pillFrame)
        self.label_5.setGeometry(QtCore.QRect(190, -30, 141, 111))
        self.label_5.setStyleSheet("  background-color: transparent;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\stars_11906616.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 30, 161, 3))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #d9c7b4;\n"
"    max-height: 1px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(890, 30, 161, 3))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #d9c7b4;\n"
"    max-height: 1px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 51, 51))
        self.label_4.setStyleSheet("  background-color: transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\social-media_13666056.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(410, 80, 711, 61))
        self.frame_5.setStyleSheet("  background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_5)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 5, 671, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAll = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonAll.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButtonAll.setObjectName("pushButtonAll")
        self.horizontalLayout.addWidget(self.pushButtonAll)
        self.pushButton5star = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton5star.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton5star.setObjectName("pushButton5star")
        self.horizontalLayout.addWidget(self.pushButton5star)
        self.pushButton4star = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton4star.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton4star.setObjectName("pushButton4star")
        self.horizontalLayout.addWidget(self.pushButton4star)
        self.pushButton3star = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton3star.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton3star.setObjectName("pushButton3star")
        self.horizontalLayout.addWidget(self.pushButton3star)
        self.pushButton2star = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton2star.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton2star.setObjectName("pushButton2star")
        self.horizontalLayout.addWidget(self.pushButton2star)
        self.pushButton1star = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton1star.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton1star.setObjectName("pushButton1star")
        self.horizontalLayout.addWidget(self.pushButton1star)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 650, 1201, 21))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #d9c7b4;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 620, 831, 20))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("  background-color: transparent;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    color: #7b6046;\n"
"    font-family: \"Inter\";\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(810, 50, 31, 31))
        self.label_6.setStyleSheet(" background-color: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\pencil.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(980, 610, 51, 41))
        self.label_7.setStyleSheet(" background-color: transparent;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\love-letter_6533269.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1060, 540, 61, 61))
        self.label_8.setStyleSheet(" background-color: transparent;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\glitter_7331135.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 120, 61, 51))
        self.label_10.setStyleSheet(" background-color: transparent;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\stars_12301787.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1070, 0, 41, 41))
        self.label_11.setStyleSheet(" background-color: transparent;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\stars_12301787.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(300, 0, 81, 81))
        self.label_13.setStyleSheet(" background-color: transparent;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C:/Users/ACER/OneDrive/Pictures/logo2.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(69, 109, 1061, 501))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_6)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 26px;\n"
"\n"
"\n"
"}\n"
"\n"
"QScrollArea QWidget {\n"
"    background: transparent;\n"
"}\n"
"")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1027, 467))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(18, 20, 20, 20)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(0, 10, 71, 41))
        self.pushButtonBack.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\Elearning\\K25411E\\Do_an\\Review\\../Login/images/arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.frame_6.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.pillFrame.raise_()
        self.label_4.raise_()
        self.frame_5.raise_()
        self.frame_2.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_2.raise_()
        self.pushButtonBack.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CUSTOMER REVIEWS "))
        self.label_2.setText(_translate("MainWindow", "“ What Our Clients Say? ”"))
        self.pillText.setText(_translate("MainWindow", "RATING"))
        self.pushButtonAll.setText(_translate("MainWindow", "All"))
        self.pushButton5star.setText(_translate("MainWindow", "⭐⭐⭐⭐⭐"))
        self.pushButton4star.setText(_translate("MainWindow", "⭐⭐⭐⭐"))
        self.pushButton3star.setText(_translate("MainWindow", "⭐⭐⭐"))
        self.pushButton2star.setText(_translate("MainWindow", "⭐⭐"))
        self.pushButton1star.setText(_translate("MainWindow", "⭐"))
        self.label_3.setText(_translate("MainWindow", "Thank you for sharing your experience with us. Every review you leave motivates us to improve every day."))
