# Form implementation generated from reading ui file '/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 772)
        MainWindow.setStyleSheet("/* ===== GLOBAL FONT ===== */\n"
"* {\n"
"    font-family: \"Playfair Display\";\n"
"}\n"
"\n"
"/* ===== PAGE BACKGROUND ===== */\n"
"QMainWindow {\n"
"    background-color: #F5EBDD;\n"
"}\n"
"\n"
"/* ===== GALLERY TITLE ===== */\n"
"#galleryTitle {\n"
"    color: #6B3F2A;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    \n"
"}\n"
"\n"
"/* ===== GALLERY FRAME (KHUNG NGOÀI) ===== */\n"
"#galleryFrame {\n"
"    background-color: #F8F1E8;\n"
"    border: 2px solid #C28B5D;    /* nâu caramel */\n"
"    border-radius: 22px;          /* bo góc ngoài */\n"
"    padding: 20px;\n"
"}\n"
"\n"
"/* ===== IMAGE BOXES — VUÔNG, KHÔNG BO GÓC ===== */\n"
"#img_1, \n"
"#img_2, \n"
"#img_3, \n"
"#img_4, \n"
"#img_5, \n"
"#img_6, \n"
"#img_7, \n"
"#img_8, \n"
"#img_9 {\n"
"    background-color: #FFF9F3;\n"
"    border: 2px solid #C28B5D;   /* màu nâu giống mẫu */\n"
"    border-radius: 0px;          /* VUÔNG hoàn toàn */\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* ===== VIEW MORE BUTTON ===== */\n"
"#viewMoreButton {\n"
"    color: #FFFFFF;\n"
"    background-color: #B8845E;\n"
"    border-radius: 24px;\n"
"    padding: 10px 35px;\n"
"    font-size: 18px;\n"
"    border: none;\n"
"}\n"
"\n"
"#viewMoreButton:hover {\n"
"    background-color: #A6734D;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -10, 161, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/ChatGPT Image Feb 12, 2026, 06_00_15 PM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, -20, 191, 111))
        self.label_2.setStyleSheet("QLabel#label_2 {\n"
"    color: #6e4c35;\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 38px;\n"
"    font-weight: 600;\n"
"    background-color:transparent;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.img_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.img_1.setGeometry(QtCore.QRect(300, 70, 261, 331))
        self.img_1.setMaximumSize(QtCore.QSize(5555555, 16777215))
        self.img_1.setText("")
        self.img_1.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/z7605046228573_f50c8f856f4df3addf716125ad51f183.png"))
        self.img_1.setScaledContents(True)
        self.img_1.setObjectName("img_1")
        self.img_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.img_3.setGeometry(QtCore.QRect(620, 70, 251, 331))
        self.img_3.setMaximumSize(QtCore.QSize(55555, 55555))
        self.img_3.setText("")
        self.img_3.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/z7605046228493_b2502f01ab46685710a569ecda6b2745.png"))
        self.img_3.setScaledContents(True)
        self.img_3.setObjectName("img_3")
        self.img_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.img_7.setGeometry(QtCore.QRect(240, 410, 221, 251))
        self.img_7.setMaximumSize(QtCore.QSize(44455, 544444))
        self.img_7.setText("")
        self.img_7.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/z7605046126575_8d54da41a26d0c3c3f12305c138c537e.png"))
        self.img_7.setScaledContents(True)
        self.img_7.setObjectName("img_7")
        self.img_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.img_8.setGeometry(QtCore.QRect(500, 410, 211, 251))
        self.img_8.setMaximumSize(QtCore.QSize(55555, 555555))
        self.img_8.setText("")
        self.img_8.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/z7605046108556_93759be82836558ea65f0fcb8a31af4b.png"))
        self.img_8.setScaledContents(True)
        self.img_8.setObjectName("img_8")
        self.img_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.img_6.setGeometry(QtCore.QRect(750, 410, 191, 251))
        self.img_6.setMaximumSize(QtCore.QSize(544444, 5444444))
        self.img_6.setText("")
        self.img_6.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/z7605046184771_48c2eda2fa3f9692a5f37787d3114db2.png"))
        self.img_6.setScaledContents(True)
        self.img_6.setObjectName("img_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 50, 71, 31))
        self.pushButton.setStyleSheet("background-color:transparent;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/gallery/../../../Downloads/left-arrow_608286.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Gallery"))
