# Form implementation generated from reading ui file 'E:\Elearning\Lumora_Studio_Booking_System\Lumora_Studio_Booking_System\guest_ui\after_booking\ui\AfterBookingMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 700))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color:#F5EDE3;\n"
"font-family:Segoe UI;\n"
"font-size:11pt;\n"
"color:#5a4632;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.headerWidget.setGeometry(QtCore.QRect(0, 10, 1200, 31))
        self.headerWidget.setStyleSheet("#headerWidget{\n"
"background-color:#C89B6D;\n"
"border:none;\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.btnNotification = QtWidgets.QLabel(parent=self.headerWidget)
        self.btnNotification.setGeometry(QtCore.QRect(90, 0, 300, 30))
        self.btnNotification.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:18pt;\n"
"font-weight:bold;\n"
"border:none;")
        self.btnNotification.setObjectName("btnNotification")
        self.frameConfirmation = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameConfirmation.setGeometry(QtCore.QRect(40, 69, 1111, 121))
        self.frameConfirmation.setStyleSheet("background-color:#f4ece5;\n"
"border:1px solid #e2d6ca;\n"
"border-radius:14px;")
        self.frameConfirmation.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameConfirmation.setObjectName("frameConfirmation")
        self.label_3 = QtWidgets.QLabel(parent=self.frameConfirmation)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 35, 10))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frameConfirmation)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 40, 40))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frameConfirmation)
        self.label_5.setGeometry(QtCore.QRect(110, 125, 35, 10))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=self.frameConfirmation)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 32, 32))
        self.label_2.setStyleSheet("border:none;\n"
"background:transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\guest_ui\\after_booking\\ui\\congratulation.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(parent=self.frameConfirmation)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 900, 35))
        self.label_6.setStyleSheet("font-size:22px;\n"
"font-weight:700;\n"
"color:#7a4e2d;\n"
"border:none;\n"
"background:transparent;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frameConfirmation)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 700, 61))
        self.label_7.setStyleSheet("font-size:14px;\n"
"color:#6d5a4a;\n"
"border:none;\n"
"background:transparent;")
        self.label_7.setObjectName("label_7")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(680, 210, 461, 401))
        self.frame_3.setStyleSheet("background-color: #FFF7F2;\n"
"border: 1px solid #E6D3C3;\n"
"border-radius: 12px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.label_28 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_28.setStyleSheet("border:none;\n"
"border-radius:12px;")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\guest_ui\\after_booking\\ui\\notice.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(60, 10, 341, 41))
        self.label_29.setStyleSheet("color:#8B5E3C;\n"
"border:none;\n"
"border-radius:12px;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_30.setGeometry(QtCore.QRect(60, 60, 10, 20))
        self.label_30.setStyleSheet("color: rgb(155, 174, 74);\n"
"\n"
"border:none;\n"
"border-radius:12px;")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(80, 60, 400, 21))
        self.label_31.setStyleSheet("\n"
"border:none;\n"
"border-radius:12px;\n"
"")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_32.setGeometry(QtCore.QRect(60, 100, 10, 20))
        self.label_32.setStyleSheet("color: rgb(155, 174, 74);\n"
"\n"
"border:none;\n"
"border-radius:12px;")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(80, 100, 400, 20))
        self.label_33.setStyleSheet("\n"
"border:none;\n"
"border-radius:12px;\n"
"")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(60, 140, 20, 20))
        self.label_34.setStyleSheet("color: rgb(155, 174, 74);\n"
"\n"
"border:none;\n"
"")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_35.setGeometry(QtCore.QRect(80, 140, 400, 20))
        self.label_35.setStyleSheet("\n"
"border:none;\n"
"border-radius:12px;\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(410, 129, 35, 31))
        self.label_22.setStyleSheet("border:none;\n"
"border-radius:12px;\n"
"")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\guest_ui\\after_booking\\ui\\photograph.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(70, 180, 321, 201))
        self.label_8.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\guest_ui\\after_booking\\ui\\../images/thank-you.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.pushButton_3.setStyleSheet("background-color: transparent;")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Admin/Downloads/left-arrow_608286.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.headerWidget_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.headerWidget_2.setGeometry(QtCore.QRect(-1, 650, 1200, 20))
        self.headerWidget_2.setStyleSheet("#headerWidget_2{\n"
"background-color:#C89B6D;\n"
"border:none;\n"
"}")
        self.headerWidget_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.headerWidget_2.setObjectName("headerWidget_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(50, 210, 611, 401))
        self.frame_5.setStyleSheet("background-color:#f3e7db;\n"
"border:1px solid #e2d6ca;\n"
"border-radius:14px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setObjectName("frame_5")
        self.textEditAppointment = QtWidgets.QTextEdit(parent=self.frame_5)
        self.textEditAppointment.setGeometry(QtCore.QRect(10, 50, 591, 301))
        self.textEditAppointment.setStyleSheet("QTextEdit{\n"
"border:1px solid #D8C4B6;\n"
"border-radius:12px;\n"
"background-color:#F8F3EE;\n"
"padding:10px;\n"
"color:#5C3A21;\n"
"}")
        self.textEditAppointment.setObjectName("textEditAppointment")
        self.label_36 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_36.setGeometry(QtCore.QRect(20, 10, 261, 41))
        self.label_36.setStyleSheet("QLabel{\n"
"border:none;\n"
"background:transparent;\n"
"color:#7A4B2A;\n"
"font-size:14pt;\n"
"font-weight:bold;\n"
"}")
        self.label_36.setObjectName("label_36")
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonConfirm.setGeometry(QtCore.QRect(310, 360, 201, 31))
        self.pushButtonConfirm.setStyleSheet("QPushButton{\n"
"background-color:#C79A6B;\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:12pt;\n"
"font-weight:600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#B88A5C;\n"
"}")
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.pushButtonEdit = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButtonEdit.setGeometry(QtCore.QRect(100, 360, 201, 31))
        self.pushButtonEdit.setStyleSheet("QPushButton{\n"
"background-color:#C79A6B;\n"
"color:white;\n"
"border-radius:10px;\n"
"font-size:12pt;\n"
"font-weight:600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#B88A5C;\n"
"}")
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 61, 61))
        self.label.setMaximumSize(QtCore.QSize(1200, 720))
        self.label.setStyleSheet("background:transparent;\n"
"border:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\guest_ui\\after_booking\\ui\\../../guest_booking/images/Subject 2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNotification.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">STUDIO LUMORA</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "THANK YOU FOR BOOKING WITH STUDIO LUMORA"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">We have received your booking information.</span></p><p><span style=\" font-size:16pt;\">Studio LUMORA will confirm your appointment shortly.</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">NOTIFICATIONS</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "●"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Your appointment has been confirmed</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "●"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Remember to arrive 15 minutes early</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "●"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Prepare appropriate outfits</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Your Appointment</span></p></body></html>"))
        self.pushButtonConfirm.setText(_translate("MainWindow", "Confirm"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Edit"))
