# Form implementation generated from reading ui file '/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginMainWindow(object):
    def setupUi(self, LoginMainWindow):
        LoginMainWindow.setObjectName("LoginMainWindow")
        LoginMainWindow.resize(1200, 720)
        LoginMainWindow.setMinimumSize(QtCore.QSize(1200, 720))
        self.centralwidget = QtWidgets.QWidget(parent=LoginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.labelThumbnail = QtWidgets.QLabel(parent=self.widget)
        self.labelThumbnail.setGeometry(QtCore.QRect(0, 330, 591, 341))
        self.labelThumbnail.setText("")
        self.labelThumbnail.setPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/thumnail.png"))
        self.labelThumbnail.setScaledContents(True)
        self.labelThumbnail.setObjectName("labelThumbnail")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(590, 0, 611, 681))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: #f5efe8;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.lineEditUser = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditUser.setGeometry(QtCore.QRect(120, 230, 421, 51))
        self.lineEditUser.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #d6c6b8;\n"
"    border-radius: 22px;\n"
"    padding: 10px 16px;\n"
"    font-size: 15px;\n"
"    color: #4b3b2f;\n"
"font-family: \"Inter\";\n"
"background-color:#f2f0ee;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #7b6046;\n"
"}\n"
"")
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEditPassword.setGeometry(QtCore.QRect(120, 310, 421, 51))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #d6c6b8;\n"
"    border-radius: 22px;\n"
"    padding: 10px 16px;\n"
"    font-size: 15px;\n"
"    color: #4b3b2f;\n"
"font-family: \"Inter\";\n"
"background-color:#f2f0ee;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #7b6046;\n"
"}\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonLogin.setGeometry(QtCore.QRect(230, 410, 171, 51))
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    background-color: #7b6046;\n"
"    color: white;\n"
"    border-radius: 24px;\n"
"    padding: 12px;\n"
"    font-size: 15px;\n"
"font-family: \"Inter\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6a533c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a4633;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/ic_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(150, 80, 321, 91))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 70px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 4px;\n"
"    color: #7b6046;\n"
"  background-color: transparent;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.labelUser = QtWidgets.QLabel(parent=self.widget_2)
        self.labelUser.setGeometry(QtCore.QRect(30, 230, 101, 61))
        self.labelUser.setStyleSheet("background-color: transparent;\n"
"")
        self.labelUser.setText("")
        self.labelUser.setPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/ic_2.png"))
        self.labelUser.setScaledContents(True)
        self.labelUser.setObjectName("labelUser")
        self.labelLock = QtWidgets.QLabel(parent=self.widget_2)
        self.labelLock.setGeometry(QtCore.QRect(30, 310, 101, 61))
        self.labelLock.setStyleSheet("background-color: transparent;\n"
"")
        self.labelLock.setText("")
        self.labelLock.setPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/ic_1.png"))
        self.labelLock.setScaledContents(True)
        self.labelLock.setObjectName("labelLock")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButtonBack.setGeometry(QtCore.QRect(20, 20, 100, 32))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(140, 20, 351, 91))
        self.label_5.setStyleSheet("QLabel {\n"
"font-family: \"Allura\";\n"
"font-size: 60px;\n"
"font-weight: normal; \n"
"    color: #7b6046;\n"
"  background-color: transparent;\n"
"}\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(60, 90, 491, 71))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 26px;\n"
"    font-weight: 600;\n"
"        color: #7b6046;\n"
"  background-color: transparent;\n"
"   letter-spacing: 1px;\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.labelSubject = QtWidgets.QLabel(parent=self.widget)
        self.labelSubject.setGeometry(QtCore.QRect(80, 10, 101, 91))
        self.labelSubject.setText("")
        self.labelSubject.setPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/Subject.png"))
        self.labelSubject.setScaledContents(True)
        self.labelSubject.setObjectName("labelSubject")
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setGeometry(QtCore.QRect(130, 180, 361, 131))
        self.label_8.setStyleSheet("\n"
"    font-family: \"Inter\";\n"
"    font-size: 16px;\n"
"        color: #7b6046;\n"
"  background-color: transparent;\n"
"\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.labelShining = QtWidgets.QLabel(parent=self.widget)
        self.labelShining.setGeometry(QtCore.QRect(150, 190, 31, 31))
        self.labelShining.setStyleSheet("background-color: transparent;\n"
"")
        self.labelShining.setText("")
        self.labelShining.setPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/ic_shining.png"))
        self.labelShining.setScaledContents(True)
        self.labelShining.setObjectName("labelShining")
        self.labelStar = QtWidgets.QLabel(parent=self.widget)
        self.labelStar.setGeometry(QtCore.QRect(460, 260, 41, 41))
        self.labelStar.setText("")
        self.labelStar.setPixmap(QtGui.QPixmap("/Users/macmall/Downloads/Lumora_Studio_Booking_System/admin_ui/login/ui/../images/ic_star.png"))
        self.labelStar.setScaledContents(True)
        self.labelStar.setObjectName("labelStar")
        self.label_10 = QtWidgets.QLabel(parent=self.widget)
        self.label_10.setGeometry(QtCore.QRect(170, 150, 271, 16))
        self.label_10.setStyleSheet("color: rgb(2, 2, 2);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        LoginMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        LoginMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginMainWindow)
        self.statusbar.setObjectName("statusbar")
        LoginMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginMainWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginMainWindow)

    def retranslateUi(self, LoginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginMainWindow.setWindowTitle(_translate("LoginMainWindow", "MainWindow"))
        self.lineEditUser.setPlaceholderText(_translate("LoginMainWindow", "Enter your username/ email"))
        self.lineEditPassword.setPlaceholderText(_translate("LoginMainWindow", "Enter your password "))
        self.pushButtonLogin.setText(_translate("LoginMainWindow", "  LOGIN"))
        self.label_2.setText(_translate("LoginMainWindow", "LOGIN"))
        self.pushButtonBack.setText(_translate("LoginMainWindow", "Back"))
        self.label_5.setText(_translate("LoginMainWindow", "LUMORA"))
        self.label_6.setText(_translate("LoginMainWindow", "- Professional photography studio -"))
        self.label_8.setText(_translate("LoginMainWindow", "Thoughtful photography services\n"
"\n"
"Capturing your most beautiful moments\n"
"\n"
"Our experienced photography team"))
        self.label_10.setText(_translate("LoginMainWindow", "──────────── ✧ ✦ ✧ ────────────"))
