# Form implementation generated from reading ui file '/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/content/ui/ContentMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 720))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(245, 238, 230);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnNotification = QtWidgets.QFrame(parent=self.centralwidget)
        self.btnNotification.setGeometry(QtCore.QRect(0, 0, 1200, 31))
        self.btnNotification.setStyleSheet("background-color: #B8946D;")
        self.btnNotification.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.btnNotification.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.btnNotification.setObjectName("btnNotification")
        self.label_43 = QtWidgets.QLabel(parent=self.btnNotification)
        self.label_43.setGeometry(QtCore.QRect(-10, 0, 91, 61))
        self.label_43.setMaximumSize(QtCore.QSize(16777204, 16777215))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/content/ui/Cắt ảnh viền tròn_files/ccd8405c-de33-4f9c-ba64-c2e37872849a.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(parent=self.btnNotification)
        self.label_44.setGeometry(QtCore.QRect(70, 0, 400, 30))
        self.label_44.setStyleSheet("color: white;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"letter-spacing: 2px;")
        self.label_44.setObjectName("label_44")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, 669, 1291, 51))
        self.frame.setStyleSheet("background-color: #B8946D;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 40, 371, 41))
        self.label.setStyleSheet("color: rgb(93, 58, 26);")
        self.label.setObjectName("label")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(30, 40, 81, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/content/ui/../../../guest_ui/contact/images/left_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(25, 90, 1151, 571))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(18, 20, 20, 20)
        self.horizontalLayout_5.setSpacing(16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_2.setStyleSheet("color: rgb(93, 58, 26);\n"
"border: transparent;\n"
"background-color: #ebd6c1;\n"
"      border-radius: 18px;\n"
"    border: 2px solid #8b6b4f;\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonDeleteAlb = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButtonDeleteAlb.setMaximumSize(QtCore.QSize(170, 40))
        self.pushButtonDeleteAlb.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#ebd6c1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background:#d9bfa4;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/content/ui/../images/bin.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDeleteAlb.setIcon(icon1)
        self.pushButtonDeleteAlb.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonDeleteAlb.setObjectName("pushButtonDeleteAlb")
        self.horizontalLayout_3.addWidget(self.pushButtonDeleteAlb)
        self.pushButtonSaveAlb = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButtonSaveAlb.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButtonSaveAlb.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#ebd6c1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background:#d9bfa4;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        self.pushButtonSaveAlb.setObjectName("pushButtonSaveAlb")
        self.horizontalLayout_3.addWidget(self.pushButtonSaveAlb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.comboBoxAlb = QtWidgets.QComboBox(parent=self.frame_6)
        self.comboBoxAlb.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxAlb.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Playfair Display")
        font.setPointSize(-1)
        self.comboBoxAlb.setFont(font)
        self.comboBoxAlb.setStyleSheet("QComboBox{\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}")
        self.comboBoxAlb.setObjectName("comboBoxAlb")
        self.horizontalLayout_3.addWidget(self.comboBoxAlb)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonDeletePhoto = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButtonDeletePhoto.setMaximumSize(QtCore.QSize(170, 40))
        self.pushButtonDeletePhoto.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#ebd6c1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background:#d9bfa4;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        self.pushButtonDeletePhoto.setIcon(icon1)
        self.pushButtonDeletePhoto.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonDeletePhoto.setObjectName("pushButtonDeletePhoto")
        self.horizontalLayout_4.addWidget(self.pushButtonDeletePhoto)
        self.pushButtonSavePhoto = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButtonSavePhoto.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#ebd6c1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background:#d9bfa4;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        self.pushButtonSavePhoto.setObjectName("pushButtonSavePhoto")
        self.horizontalLayout_4.addWidget(self.pushButtonSavePhoto)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_6)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -247, 665, 582))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridGallery = QtWidgets.QGridLayout()
        self.gridGallery.setObjectName("gridGallery")
        self.label_photo2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_photo2.setMinimumSize(QtCore.QSize(180, 180))
        self.label_photo2.setMaximumSize(QtCore.QSize(180, 180))
        self.label_photo2.setStyleSheet("#label_photo2 {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_photo2.setText("")
        self.label_photo2.setObjectName("label_photo2")
        self.gridGallery.addWidget(self.label_photo2, 0, 1, 1, 1)
        self.label_photo3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_photo3.setMinimumSize(QtCore.QSize(180, 180))
        self.label_photo3.setMaximumSize(QtCore.QSize(180, 180))
        self.label_photo3.setStyleSheet("#label_photo3 {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_photo3.setText("")
        self.label_photo3.setObjectName("label_photo3")
        self.gridGallery.addWidget(self.label_photo3, 0, 2, 1, 1)
        self.label_photo1 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_photo1.setMinimumSize(QtCore.QSize(180, 180))
        self.label_photo1.setMaximumSize(QtCore.QSize(180, 180))
        self.label_photo1.setStyleSheet("#label_photo1 {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_photo1.setText("")
        self.label_photo1.setObjectName("label_photo1")
        self.gridGallery.addWidget(self.label_photo1, 0, 0, 1, 1)
        self.label_photo6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_photo6.setMinimumSize(QtCore.QSize(180, 180))
        self.label_photo6.setMaximumSize(QtCore.QSize(180, 180))
        self.label_photo6.setStyleSheet("#label_photo6 {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_photo6.setText("")
        self.label_photo6.setObjectName("label_photo6")
        self.gridGallery.addWidget(self.label_photo6, 1, 2, 1, 1)
        self.label_photo5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_photo5.setMinimumSize(QtCore.QSize(180, 180))
        self.label_photo5.setMaximumSize(QtCore.QSize(180, 180))
        self.label_photo5.setStyleSheet("#label_photo5 {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_photo5.setText("")
        self.label_photo5.setObjectName("label_photo5")
        self.gridGallery.addWidget(self.label_photo5, 1, 1, 1, 1)
        self.label_photo4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_photo4.setMinimumSize(QtCore.QSize(180, 180))
        self.label_photo4.setMaximumSize(QtCore.QSize(180, 180))
        self.label_photo4.setStyleSheet("#label_photo4 {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_photo4.setText("")
        self.label_photo4.setObjectName("label_photo4")
        self.gridGallery.addWidget(self.label_photo4, 1, 0, 1, 1)
        self.label_add_photo = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_add_photo.setMinimumSize(QtCore.QSize(180, 180))
        self.label_add_photo.setMaximumSize(QtCore.QSize(180, 180))
        self.label_add_photo.setStyleSheet("#label_add_photo {\n"
"    border-radius: 0px;\n"
"    border: 2px solid #C28B5D;   /* nâu caramen */\n"
"    background-color: #FFF9F3;   /* nền nhẹ */\n"
"}")
        self.label_add_photo.setText("")
        self.label_add_photo.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/content/ui/../images/add.png"))
        self.label_add_photo.setScaledContents(True)
        self.label_add_photo.setObjectName("label_add_photo")
        self.gridGallery.addWidget(self.label_add_photo, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridGallery)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayoutReviews = QtWidgets.QVBoxLayout()
        self.verticalLayoutReviews.setObjectName("verticalLayoutReviews")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_3.setStyleSheet("color: rgb(93, 58, 26);\n"
"border: transparent;\n"
"background-color: #ebd6c1;\n"
"      border-radius: 18px;\n"
"    border: 2px solid #8b6b4f;\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayoutReviews.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonDeleteReview = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButtonDeleteReview.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        self.pushButtonDeleteReview.setObjectName("pushButtonDeleteReview")
        self.horizontalLayout_2.addWidget(self.pushButtonDeleteReview)
        self.comboBoxRating = QtWidgets.QComboBox(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Playfair Display")
        font.setPointSize(-1)
        self.comboBoxRating.setFont(font)
        self.comboBoxRating.setStyleSheet("QComboBox{\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}")
        self.comboBoxRating.setObjectName("comboBoxRating")
        self.horizontalLayout_2.addWidget(self.comboBoxRating)
        self.verticalLayoutReviews.addLayout(self.horizontalLayout_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.frame_6)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 376, 371))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frameFeedback_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.frameFeedback_4.setMaximumSize(QtCore.QSize(900, 200))
        self.frameFeedback_4.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"")
        self.frameFeedback_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameFeedback_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameFeedback_4.setObjectName("frameFeedback_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameFeedback_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.nameLabel_7 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.nameLabel_7.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.nameLabel_7.setObjectName("nameLabel_7")
        self.gridLayout_6.addWidget(self.nameLabel_7, 0, 0, 1, 1)
        self.nameLineEdit_7 = QtWidgets.QLineEdit(parent=self.frameFeedback_4)
        self.nameLineEdit_7.setObjectName("nameLineEdit_7")
        self.gridLayout_6.addWidget(self.nameLineEdit_7, 0, 1, 1, 1)
        self.emailLabel_7 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.emailLabel_7.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.emailLabel_7.setObjectName("emailLabel_7")
        self.gridLayout_6.addWidget(self.emailLabel_7, 1, 0, 1, 1)
        self.emailLineEdit_7 = QtWidgets.QLineEdit(parent=self.frameFeedback_4)
        self.emailLineEdit_7.setObjectName("emailLineEdit_7")
        self.gridLayout_6.addWidget(self.emailLineEdit_7, 1, 1, 1, 1)
        self.feedbackLabel_9 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.feedbackLabel_9.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.feedbackLabel_9.setObjectName("feedbackLabel_9")
        self.gridLayout_6.addWidget(self.feedbackLabel_9, 2, 0, 1, 1)
        self.rating_5 = QtWidgets.QLineEdit(parent=self.frameFeedback_4)
        self.rating_5.setObjectName("rating_5")
        self.gridLayout_6.addWidget(self.rating_5, 2, 1, 1, 1)
        self.feedbackLabel_10 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.feedbackLabel_10.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.feedbackLabel_10.setObjectName("feedbackLabel_10")
        self.gridLayout_6.addWidget(self.feedbackLabel_10, 3, 0, 1, 1)
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.frameFeedback_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_7.sizePolicy().hasHeightForWidth())
        self.textEdit_7.setSizePolicy(sizePolicy)
        self.textEdit_7.setMaximumSize(QtCore.QSize(350, 100))
        self.textEdit_7.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.textEdit_7.setPlaceholderText("")
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout_6.addWidget(self.textEdit_7, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.verticalLayout_5.addWidget(self.frameFeedback_4)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayoutReviews.addWidget(self.scrollArea_3)
        self.horizontalLayout_5.addLayout(self.verticalLayoutReviews)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_44.setText(_translate("MainWindow", "STUDIO LUMORA"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">Content Management</span></p></body></html>"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Gallery</span></p></body></html>"))
        self.pushButtonDeleteAlb.setText(_translate("MainWindow", "Delete Album"))
        self.pushButtonSaveAlb.setText(_translate("MainWindow", "Update Album"))
        self.pushButtonDeletePhoto.setText(_translate("MainWindow", "Delete Photo"))
        self.pushButtonSavePhoto.setText(_translate("MainWindow", "Update Photo"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Reviews</span></p></body></html>"))
        self.pushButtonDeleteReview.setText(_translate("MainWindow", "Delete"))
        self.nameLabel_7.setText(_translate("MainWindow", "Name:"))
        self.emailLabel_7.setText(_translate("MainWindow", "Email:"))
        self.feedbackLabel_9.setText(_translate("MainWindow", "Rating"))
        self.feedbackLabel_10.setText(_translate("MainWindow", "Review"))
