# Form implementation generated from reading ui file '/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/admin_ui/add_appoint/ui/AddAppointmentMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 592)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #fbf5e9;\n"
"    font-family: \"Inter\";\n"
"    color: #3a2e24;\n"
"}\n"
"\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_title.setMinimumSize(QtCore.QSize(450, 50))
        self.lbl_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbl_title.setStyleSheet("QLabel {\n"
"    background-color: #b08968;\n"
"    border-radius: 14px;\n"
"    color: #ffffff;\n"
"font-family: \"Playfair Display\";\n"
"    font-size: 30px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0px;\n"
"}")
        self.lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.frame_form_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_form_left.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"")
        self.frame_form_left.setObjectName("frame_form_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_form_left)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_7.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBoxConcept = QtWidgets.QComboBox(parent=self.frame_form_left)
        self.comboBoxConcept.setStyleSheet("QComboBox{\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QComboBox:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.comboBoxConcept.setObjectName("comboBoxConcept")
        self.gridLayout_2.addWidget(self.comboBoxConcept, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_8.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_17.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_10.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_21.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 12, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.frame_form_left)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 7, 0, 1, 2)
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.frame_form_left)
        self.timeEdit.setStyleSheet("QTimeEdit{\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QTimeEdit:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_19.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 0, 1, 1)
        self.lineEditNotes = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditNotes.setObjectName("lineEditNotes")
        self.gridLayout_2.addWidget(self.lineEditNotes, 13, 1, 1, 1)
        self.lineEditEmail_2 = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditEmail_2.setObjectName("lineEditEmail_2")
        self.gridLayout_2.addWidget(self.lineEditEmail_2, 2, 1, 1, 1)
        self.lineEditName_2 = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditName_2.setObjectName("lineEditName_2")
        self.gridLayout_2.addWidget(self.lineEditName_2, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_18.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 8, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frame_form_left)
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QDateEdit:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 5, 1, 1, 1)
        self.lineEditPhone_2 = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditPhone_2.setObjectName("lineEditPhone_2")
        self.gridLayout_2.addWidget(self.lineEditPhone_2, 3, 1, 1, 1)
        self.lineEditPromo = QtWidgets.QLineEdit(parent=self.frame_form_left)
        self.lineEditPromo.setObjectName("lineEditPromo")
        self.gridLayout_2.addWidget(self.lineEditPromo, 12, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_form_left)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 2)
        self.comboBoxQuantity = QtWidgets.QComboBox(parent=self.frame_form_left)
        self.comboBoxQuantity.setStyleSheet("QComboBox{\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QComboBox:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.comboBoxQuantity.setObjectName("comboBoxQuantity")
        self.gridLayout_2.addWidget(self.comboBoxQuantity, 11, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_22.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 13, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_9.setStyleSheet("\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.comboBoxPackage = QtWidgets.QComboBox(parent=self.frame_form_left)
        self.comboBoxPackage.setStyleSheet("QComboBox{\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QComboBox:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.comboBoxPackage.setObjectName("comboBoxPackage")
        self.gridLayout_2.addWidget(self.comboBoxPackage, 8, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_23.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 11, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_form_left)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 2)
        self.label_33 = QtWidgets.QLabel(parent=self.frame_form_left)
        self.label_33.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"font-size: 16px;\n"
"    color: rgb(3, 3, 3);\n"
"font-family: \"Inter\";\n"
"}")
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 10, 0, 1, 1)
        self.comboBoxLocation = QtWidgets.QComboBox(parent=self.frame_form_left)
        self.comboBoxLocation.setStyleSheet("QComboBox{\n"
"    background-color: #fdf8f3;\n"
"    border: 1.5px solid #c8a98d;\n"
"    border-radius: 12px;\n"
"    padding-left: 12px;\n"
"    font: 14px \"Playfair Display\";\n"
"    color: #4e342e;\n"
"}\n"
"\n"
"QComboBox:placeholder {\n"
"    color: #a67c5b;  \n"
"}")
        self.comboBoxLocation.setObjectName("comboBoxLocation")
        self.gridLayout_2.addWidget(self.comboBoxLocation, 10, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.frame_form_left)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(True)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_form_left)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:30pt;\">Booking Addition</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Customer:"))
        self.label_8.setText(_translate("MainWindow", "Email:"))
        self.label_17.setText(_translate("MainWindow", "Time:"))
        self.label_10.setText(_translate("MainWindow", "Date:"))
        self.label_21.setText(_translate("MainWindow", "Promo:"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">SERVICE </span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Concept:"))
        self.label_18.setText(_translate("MainWindow", "Package:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">SHOOTING TIME</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Notes:"))
        self.label_9.setText(_translate("MainWindow", "Phone number:"))
        self.label_23.setText(_translate("MainWindow", "Quantity:"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">CUSTOMER DETAILS</span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "Location:"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add"))
