# Form implementation generated from reading ui file 'E:\Elearning\Lumora_Studio_Booking_System\Lumora_Studio_Booking_System\admin_ui\cus_information\ui\CustomerMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 720)
        Form.setMinimumSize(QtCore.QSize(1200, 720))
        Form.setStyleSheet("background-color:#F5EEE6;")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.frame.setStyleSheet("background-color: #B08968;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 90, 1161, 581))
        self.widget.setMinimumSize(QtCore.QSize(250, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(230, 40, 931, 561))
        self.widget_2.setObjectName("widget_2")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(380, 150, 21, 20))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: #5A3E2B;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("C:/Users/Admin/.designer/backup/7334113.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 891, 141))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #F1E3D3;\n"
"    border: 1px solid #D1B89C;\n"
"    border-radius: 12px;\n"
"    margin-top: 12px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    top: -8px;\n"
"    padding: 0 6px;\n"
"    color: #5A3E2B;\n"
"    font-weight: bold;\n"
"    background-color: #F6EFE7;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 131, 111))
        self.label_2.setStyleSheet("border: 2px solid #D1B89C;\n"
"border-radius: 10px;\n"
"background-color: #EEE;")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\cus_information\\ui\\../images/user (1).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(180, 20, 80, 30))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #6B3E26;        /* nâu đậm giống mẫu */\n"
"    font-size: 14px;       /* chữ vừa, không to quá */\n"
"    font-weight: 600;      /* hơi đậm */\n"
"}\n"
"QLabel{\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(180, 60, 80, 30))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: #6B3E26;        /* nâu đậm giống mẫu */\n"
"    font-size: 14px;       /* chữ vừa, không to quá */\n"
"    font-weight: 600;      /* hơi đậm */\n"
"}\n"
"QLabel{\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(180, 100, 80, 30))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: #6B3E26;        /* nâu đậm giống mẫu */\n"
"    font-size: 14px;       /* chữ vừa, không to quá */\n"
"    font-weight: 600;      /* hơi đậm */\n"
"}\n"
"QLabel{\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditName.setGeometry(QtCore.QRect(250, 20, 621, 30))
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    background: #FFF9F3;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #6B3F1D;\n"
"    border: 2px solid #B8926F;\n"
"    background: #FFFFFF;\n"
"}")
        self.lineEditName.setReadOnly(False)
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPhone.setGeometry(QtCore.QRect(250, 60, 621, 30))
        self.lineEditPhone.setStyleSheet("QLineEdit {\n"
"    background: #FFF9F3;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #6B3F1D;\n"
"    border: 2px solid #B8926F;\n"
"    background: #FFFFFF;\n"
"}")
        self.lineEditPhone.setReadOnly(False)
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditEmail.setGeometry(QtCore.QRect(250, 100, 621, 30))
        self.lineEditEmail.setStyleSheet("QLineEdit {\n"
"    background: #FFF9F3;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #6B3F1D;\n"
"    border: 2px solid #B8926F;\n"
"    background: #FFFFFF;\n"
"}")
        self.lineEditEmail.setReadOnly(False)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 470, 550, 30))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background: #FFF9F3;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #6B3F1D;\n"
"    border: 2px solid #B8926F;\n"
"    background: #FFFFFF;\n"
"}")
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.widget_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 911, 401))
        self.groupBox_3.setStyleSheet("QTableWidget {\n"
"    background-color: #FFF9F3;\n"
"    border: 1px solid #D1B89C;\n"
"    border-radius: 10px;\n"
"    gridline-color: #E0CBB2;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #E6D1B8;\n"
"    color: #5A3E2B;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 6px;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #6B3F1D;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonStatistics = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonStatistics.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    color: #8B5A2B;\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    padding: 4px 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #6B3F1D;\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #5A3418;\n"
"}")
        self.pushButtonStatistics.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButtonStatistics.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonStatistics.setObjectName("pushButtonStatistics")
        self.horizontalLayout.addWidget(self.pushButtonStatistics)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidgetBooking = QtWidgets.QTableWidget(parent=self.groupBox_3)
        self.tableWidgetBooking.setStyleSheet("QTableWidget {\n"
"    background: #FFFDF9;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D1B89C;\n"
"    border-radius: 10px;\n"
"    gridline-color: #E6D6C6;\n"
"    font-size: 14px;\n"
"    font-family: \"Times New Roman\";\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: #6B3F1D;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #EAD8C0;\n"
"    color: #5A3E2B;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    border: none;\n"
"}")
        self.tableWidgetBooking.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidgetBooking.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidgetBooking.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetBooking.setShowGrid(True)
        self.tableWidgetBooking.setRowCount(7)
        self.tableWidgetBooking.setColumnCount(5)
        self.tableWidgetBooking.setObjectName("tableWidgetBooking")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBooking.setHorizontalHeaderItem(4, item)
        self.tableWidgetBooking.horizontalHeader().setDefaultSectionSize(113)
        self.tableWidgetBooking.horizontalHeader().setMinimumSectionSize(24)
        self.tableWidgetBooking.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetBooking.verticalHeader().setDefaultSectionSize(50)
        self.tableWidgetBooking.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetBooking.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidgetBooking)
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setGeometry(QtCore.QRect(240, 10, 21, 20))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #5A3E2B;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:/Users/Admin/.designer/backup/7334113.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.frame_3 = QtWidgets.QFrame(parent=self.widget)
        self.frame_3.setGeometry(QtCore.QRect(10, 40, 201, 541))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    background: #FFF9F3;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    color: #6B3F1D;\n"
"    border: 2px solid #B8926F;\n"
"    background: #FFFFFF;\n"
"}")
        self.lineEditSearch.setReadOnly(False)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout.addWidget(self.lineEditSearch)
        self.listWidgetCustomers = QtWidgets.QListWidget(parent=self.frame_3)
        self.listWidgetCustomers.setStyleSheet("QListWidget {\n"
"    background-color: #FFF9F3;\n"
"    color: #6B3F1D;\n"
"    border: 1.5px solid #D1B89C;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 10px;\n"
"    color: #6B3F1D;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #B7926F;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #F0E0CD;\n"
"}")
        self.listWidgetCustomers.setObjectName("listWidgetCustomers")
        self.verticalLayout.addWidget(self.listWidgetCustomers)
        self.label_14 = QtWidgets.QLabel(parent=self.widget)
        self.label_14.setGeometry(QtCore.QRect(30, 5, 260, 42))
        self.label_14.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #6B3F1D;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(parent=self.widget)
        self.label_13.setGeometry(QtCore.QRect(250, 10, 280, 42))
        self.label_13.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #6B3F1D;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 690, 1200, 20))
        self.frame_2.setStyleSheet("background-color: #B08968;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(110, 10, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;\n"
"font: 8pt \"Times New Roman\";\n"
"font-size: 20px;\n"
"font-weight: bold;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(250, 36, 900, 56))
        font = QtGui.QFont()
        font.setFamily("Playfair Display")
        font.setPointSize(-1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    font-size: 34px;\n"
"    font-weight: 700;\n"
"    color: #6B3F1D;\n"
"    letter-spacing: 1px;\n"
"    font-family: \"Playfair Display\";\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButtonBack = QtWidgets.QPushButton(parent=Form)
        self.pushButtonBack.setGeometry(QtCore.QRect(30, 38, 121, 41))
        self.pushButtonBack.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    color: #8B5A2B;\n"
"    border: none;\n"
"    font-family: \"Times New Roman\";\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #6B3F1D;\n"
"    text-decoration: underline;\n"
"    background: transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #5A3418;\n"
"    background: transparent;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\cus_information\\ui\\../../../guest_ui/contact/images/left_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setObjectName("pushButtonBack")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Name:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Phone:</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Email:</span></p></body></html>"))
        self.lineEditName.setPlaceholderText(_translate("Form", "Enter customer name"))
        self.lineEditPhone.setPlaceholderText(_translate("Form", "Phone number"))
        self.lineEditEmail.setPlaceholderText(_translate("Form", "Email address"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Customer address"))
        self.label_7.setText(_translate("Form", "Booking History"))
        self.pushButtonStatistics.setText(_translate("Form", "Statistics"))
        item = self.tableWidgetBooking.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Date"))
        item = self.tableWidgetBooking.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Quantity"))
        item = self.tableWidgetBooking.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Session type"))
        item = self.tableWidgetBooking.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Concept"))
        item = self.tableWidgetBooking.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Status"))
        self.lineEditSearch.setPlaceholderText(_translate("Form", "Search"))
        self.label_14.setText(_translate("Form", "Customer List"))
        self.label_13.setText(_translate("Form", "Customer Details"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "Customer\'s Information Management"))
        self.pushButtonBack.setText(_translate("Form", "Back"))
