# Form implementation generated from reading ui file '/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/ReviewMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 700))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #f4efe9;\n"
"    font-size: 14px;\n"
"    color: #4a3b2c;\n"
"}\n"
"QFrame#pillFrame {\n"
"    background-color: #ebd6c1;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel#pillText {\n"
"    background-color: transparent;\n"
"    color: #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 0, 571, 41))
        self.label.setStyleSheet("QLabel {\n"
"    font-family: \"Playfair Display\";\n"
"    font-size: 42px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 2px;\n"
"    color: #7b6046;\n"
"  background-color: transparent;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Allura")
        font.setPointSize(-1)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 28px;\n"
"font-family: \"Allura\";\n"
"    font-style: italic;\n"
"    font-weight: 600;\n"
"    color: #5a4332;\n"
"    letter-spacing: 5px;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pillFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.pillFrame.setGeometry(QtCore.QRect(90, 90, 341, 41))
        self.pillFrame.setStyleSheet("QFrame#pillFrame {\n"
"    background-color: #ebd6c1;\n"
"      border-radius: 18px;\n"
"    border: 2px solid #8b6b4f;\n"
"    padding: 50px;\n"
"}")
        self.pillFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pillFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pillFrame.setObjectName("pillFrame")
        self.pillText = QtWidgets.QLabel(parent=self.pillFrame)
        self.pillText.setGeometry(QtCore.QRect(60, 0, 141, 41))
        self.pillText.setAccessibleDescription("")
        self.pillText.setAutoFillBackground(False)
        self.pillText.setStyleSheet("  background-color: transparent;\n"
"    font-size: 25px;\n"
"    font-weight: 700;\n"
"    color: #7b6046;\n"
"    font-family: \"Inter\";\n"
"")
        self.pillText.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pillText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pillText.setObjectName("pillText")
        self.label_5 = QtWidgets.QLabel(parent=self.pillFrame)
        self.label_5.setGeometry(QtCore.QRect(180, -40, 151, 131))
        self.label_5.setStyleSheet("  background-color: transparent;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/stars_11906616.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 30, 161, 3))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #d9c7b4;\n"
"    max-height: 1px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(890, 30, 161, 3))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: #d9c7b4;\n"
"    max-height: 1px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 51, 51))
        self.label_4.setStyleSheet("  background-color: transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/social-media_13666056.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 650, 1201, 21))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #d9c7b4;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 620, 831, 20))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("  background-color: transparent;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    color: #7b6046;\n"
"    font-family: \"Inter\";\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(820, 50, 31, 31))
        self.label_6.setStyleSheet(" background-color: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/pencil.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(980, 610, 51, 41))
        self.label_7.setStyleSheet(" background-color: transparent;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/love-letter_6533269.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1030, 540, 61, 61))
        self.label_8.setStyleSheet(" background-color: transparent;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/glitter_7331135.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 120, 61, 51))
        self.label_10.setStyleSheet(" background-color: transparent;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/stars_12301787.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1070, 0, 41, 41))
        self.label_11.setStyleSheet(" background-color: transparent;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/stars_12301787.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(300, 0, 81, 81))
        self.label_13.setStyleSheet(" background-color: transparent;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../images/Subject 2.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(69, 109, 1071, 501))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_6)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 26px;\n"
"\n"
"\n"
"}\n"
"\n"
"QScrollArea QWidget {\n"
"    background: transparent;\n"
"}\n"
"")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1035, 465))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(18, 20, 20, 20)
        self.horizontalLayout_5.setSpacing(16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayoutReviews = QtWidgets.QVBoxLayout()
        self.verticalLayoutReviews.setObjectName("verticalLayoutReviews")
        self.frameFeedback_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frameFeedback_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frameFeedback_4.setMaximumSize(QtCore.QSize(400, 200))
        self.frameFeedback_4.setStyleSheet("QFrame {\n"
"    background-color: #fffdf8;\n"
"    border: 2px solid #7b6046;\n"
"    border-radius: 28px;\n"
" padding: 2px;\n"
"}\n"
"")
        self.frameFeedback_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameFeedback_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameFeedback_4.setObjectName("frameFeedback_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameFeedback_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.nameLabel_7 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.nameLabel_7.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.nameLabel_7.setObjectName("nameLabel_7")
        self.gridLayout_6.addWidget(self.nameLabel_7, 0, 0, 1, 1)
        self.nameLineEdit_7 = QtWidgets.QLineEdit(parent=self.frameFeedback_4)
        self.nameLineEdit_7.setObjectName("nameLineEdit_7")
        self.gridLayout_6.addWidget(self.nameLineEdit_7, 0, 1, 1, 1)
        self.emailLabel_7 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.emailLabel_7.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.emailLabel_7.setObjectName("emailLabel_7")
        self.gridLayout_6.addWidget(self.emailLabel_7, 1, 0, 1, 1)
        self.emailLineEdit_7 = QtWidgets.QLineEdit(parent=self.frameFeedback_4)
        self.emailLineEdit_7.setObjectName("emailLineEdit_7")
        self.gridLayout_6.addWidget(self.emailLineEdit_7, 1, 1, 1, 1)
        self.feedbackLabel_9 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.feedbackLabel_9.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.feedbackLabel_9.setObjectName("feedbackLabel_9")
        self.gridLayout_6.addWidget(self.feedbackLabel_9, 2, 0, 1, 1)
        self.rating_5 = QtWidgets.QLineEdit(parent=self.frameFeedback_4)
        self.rating_5.setObjectName("rating_5")
        self.gridLayout_6.addWidget(self.rating_5, 2, 1, 1, 1)
        self.feedbackLabel_10 = QtWidgets.QLabel(parent=self.frameFeedback_4)
        self.feedbackLabel_10.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.feedbackLabel_10.setObjectName("feedbackLabel_10")
        self.gridLayout_6.addWidget(self.feedbackLabel_10, 3, 0, 1, 1)
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.frameFeedback_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_7.sizePolicy().hasHeightForWidth())
        self.textEdit_7.setSizePolicy(sizePolicy)
        self.textEdit_7.setMaximumSize(QtCore.QSize(350, 100))
        self.textEdit_7.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.textEdit_7.setPlaceholderText("")
        self.textEdit_7.setObjectName("textEdit_7")
        self.gridLayout_6.addWidget(self.textEdit_7, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.verticalLayoutReviews.addWidget(self.frameFeedback_4)
        self.horizontalLayout_5.addLayout(self.verticalLayoutReviews)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout_8.setRowWrapPolicy(QtWidgets.QFormLayout.RowWrapPolicy.WrapAllRows)
        self.formLayout_8.setSpacing(0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_15 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_15.setStyleSheet(" background: transparent;\n"
"font: 14pt \"Playfair Display\";\n"
"    font-weight: 600;\n"
"    color: #7b6046;\n"
"  background-color: transparent;\n"
"   border: none;")
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_15)
        self.nameLabel_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.nameLabel_4.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.nameLabel_4.setObjectName("nameLabel_4")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel_4)
        self.nameLineEdit_4 = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.nameLineEdit_4.setObjectName("nameLineEdit_4")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameLineEdit_4)
        self.emailLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.emailLabel.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emailLabel)
        self.emailLineEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailLineEdit)
        self.ratingLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.ratingLabel.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.ratingLabel.setObjectName("ratingLabel")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ratingLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout_6.setContentsMargins(6, -1, 20, -1)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton1star = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton1star.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.pushButton1star.setCheckable(True)
        self.pushButton1star.setObjectName("pushButton1star")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton1star)
        self.horizontalLayout_6.addWidget(self.pushButton1star)
        self.pushButton2star = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton2star.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.pushButton2star.setCheckable(True)
        self.pushButton2star.setObjectName("pushButton2star")
        self.buttonGroup.addButton(self.pushButton2star)
        self.horizontalLayout_6.addWidget(self.pushButton2star)
        self.pushButton3star = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton3star.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.pushButton3star.setCheckable(True)
        self.pushButton3star.setObjectName("pushButton3star")
        self.buttonGroup.addButton(self.pushButton3star)
        self.horizontalLayout_6.addWidget(self.pushButton3star)
        self.pushButton4star = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton4star.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.pushButton4star.setCheckable(True)
        self.pushButton4star.setObjectName("pushButton4star")
        self.buttonGroup.addButton(self.pushButton4star)
        self.horizontalLayout_6.addWidget(self.pushButton4star)
        self.pushButton5star = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton5star.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.pushButton5star.setCheckable(True)
        self.pushButton5star.setObjectName("pushButton5star")
        self.buttonGroup.addButton(self.pushButton5star)
        self.horizontalLayout_6.addWidget(self.pushButton5star)
        self.formLayout_8.setLayout(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        self.reviewLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.reviewLabel.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.reviewLabel.setObjectName("reviewLabel")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.reviewLabel)
        self.textEdit = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(350, 100))
        self.textEdit.setStyleSheet(" background: transparent;\n"
"    border: none;")
        self.textEdit.setObjectName("textEdit")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonSubmit = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButtonSubmit.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.horizontalLayout_7.addWidget(self.pushButtonSubmit)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButtonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #fbf5e9;\n"
" font-family: \"Playfair Display\";\n"
"    color:  #7b6046;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 22px;\n"
"    border-radius: 18px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1\n"
";\n"
"}\n"
"")
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_7.addWidget(self.pushButtonCancel)
        self.formLayout_8.setLayout(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.formLayout_8)
        self.verticalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(0, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButtonBack.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/macmall/Desktop/ProgrammingTechniques/PythonProject/Lumora_Studio_Booking_System/guest_ui/review/ui/../../contact/images/left_arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButton1starFilter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton1starFilter.setGeometry(QtCore.QRect(1006, 92, 83, 36))
        self.pushButton1starFilter.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton1starFilter.setObjectName("pushButton1starFilter")
        self.pushButton2starFilter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2starFilter.setGeometry(QtCore.QRect(909, 92, 83, 36))
        self.pushButton2starFilter.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton2starFilter.setObjectName("pushButton2starFilter")
        self.pushButton3starFilter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton3starFilter.setGeometry(QtCore.QRect(806, 92, 89, 36))
        self.pushButton3starFilter.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton3starFilter.setObjectName("pushButton3starFilter")
        self.pushButton5starFilter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton5starFilter.setGeometry(QtCore.QRect(537, 92, 131, 36))
        self.pushButton5starFilter.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton5starFilter.setObjectName("pushButton5starFilter")
        self.pushButtonAll = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAll.setGeometry(QtCore.QRect(440, 90, 83, 40))
        self.pushButtonAll.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButtonAll.setObjectName("pushButtonAll")
        self.pushButton4starFilter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton4starFilter.setGeometry(QtCore.QRect(682, 92, 110, 36))
        self.pushButton4starFilter.setStyleSheet("QPushButton {\n"
"    font-size: 15px;\n"
"font-family:\"Inter\";\n"
"    font-weight: bold;\n"
"    background-color: #fffdf9;\n"
"    color: #7b6046;\n"
"    padding: 8px 12px;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #8b6b4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ebd6c1;\n"
"}\n"
"\n"
"")
        self.pushButton4starFilter.setObjectName("pushButton4starFilter")
        self.frame_6.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_2.raise_()
        self.pushButtonBack.raise_()
        self.pillFrame.raise_()
        self.label_4.raise_()
        self.pushButton1starFilter.raise_()
        self.pushButton2starFilter.raise_()
        self.pushButton3starFilter.raise_()
        self.pushButton5starFilter.raise_()
        self.pushButtonAll.raise_()
        self.pushButton4starFilter.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CUSTOMER REVIEWS "))
        self.label_2.setText(_translate("MainWindow", "“ What Our Clients Say? ”"))
        self.pillText.setText(_translate("MainWindow", "RATING"))
        self.label_3.setText(_translate("MainWindow", "Thank you for sharing your experience with us. Every review you leave motivates us to improve every day."))
        self.nameLabel_7.setText(_translate("MainWindow", "Name"))
        self.emailLabel_7.setText(_translate("MainWindow", "Email:"))
        self.feedbackLabel_9.setText(_translate("MainWindow", "Rating"))
        self.feedbackLabel_10.setText(_translate("MainWindow", "Review"))
        self.label_15.setText(_translate("MainWindow", "SUBMIT YOUR REVIEW"))
        self.nameLabel_4.setText(_translate("MainWindow", "Name:"))
        self.emailLabel.setText(_translate("MainWindow", "Email:"))
        self.ratingLabel.setText(_translate("MainWindow", "Rating"))
        self.pushButton1star.setText(_translate("MainWindow", "☆"))
        self.pushButton2star.setText(_translate("MainWindow", "☆"))
        self.pushButton3star.setText(_translate("MainWindow", "☆"))
        self.pushButton4star.setText(_translate("MainWindow", "☆"))
        self.pushButton5star.setText(_translate("MainWindow", "☆"))
        self.reviewLabel.setText(_translate("MainWindow", "Review"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Write your review in here..."))
        self.pushButtonSubmit.setText(_translate("MainWindow", "Submit"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
        self.pushButton1starFilter.setText(_translate("MainWindow", "⭐"))
        self.pushButton2starFilter.setText(_translate("MainWindow", "⭐⭐"))
        self.pushButton3starFilter.setText(_translate("MainWindow", "⭐⭐⭐"))
        self.pushButton5starFilter.setText(_translate("MainWindow", "⭐⭐⭐⭐⭐"))
        self.pushButtonAll.setText(_translate("MainWindow", "All"))
        self.pushButton4starFilter.setText(_translate("MainWindow", "⭐⭐⭐⭐"))
