# Form implementation generated from reading ui file 'E:\Elearning\Lumora_Studio_Booking_System\Lumora_Studio_Booking_System\admin_ui\home_admin\ui\AdminHomeMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1203, 720)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 50, 201, 661))
        self.widget.setStyleSheet("background-color:#C89B6D;\n"
"border-right: 1px solid #E0C2A8;")
        self.widget.setObjectName("widget")
        self.pushButtonDashBoard = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonDashBoard.setGeometry(QtCore.QRect(0, 50, 201, 40))
        self.pushButtonDashBoard.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonDashBoard.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 20px;\n"
"    font-size: 18px;\n"
"    color: #6B4A2D;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EEDBC7;\n"
"    border-radius: 10px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDashBoard.setIcon(icon)
        self.pushButtonDashBoard.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonDashBoard.setObjectName("pushButtonDashBoard")
        self.pushButtonAppointments = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonAppointments.setGeometry(QtCore.QRect(0, 90, 201, 40))
        self.pushButtonAppointments.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 20px;\n"
"    font-size: 18px;\n"
"    color: #6B4A2D;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EEDBC7;\n"
"    border-radius: 10px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/schedule.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAppointments.setIcon(icon1)
        self.pushButtonAppointments.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonAppointments.setObjectName("pushButtonAppointments")
        self.pushButtonCustomers = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonCustomers.setGeometry(QtCore.QRect(0, 130, 201, 40))
        self.pushButtonCustomers.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 20px;\n"
"    font-size: 18px;\n"
"    color: #6B4A2D;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EEDBC7;\n"
"    border-radius: 10px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/customer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCustomers.setIcon(icon2)
        self.pushButtonCustomers.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonCustomers.setObjectName("pushButtonCustomers")
        self.pushButtonGallery = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonGallery.setGeometry(QtCore.QRect(0, 170, 201, 40))
        self.pushButtonGallery.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 20px;\n"
"    font-size: 18px;\n"
"    color: #6B4A2D;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EEDBC7;\n"
"    border-radius: 10px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/content-creation.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonGallery.setIcon(icon3)
        self.pushButtonGallery.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonGallery.setObjectName("pushButtonGallery")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(-1, 220, 201, 40))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 20px;\n"
"    font-size: 18px;\n"
"    color: #6B4A2D;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #EEDBC7;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #F0D9BE;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/admin-home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButtonLogOut = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonLogOut.setGeometry(QtCore.QRect(0, 580, 201, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogOut.setFont(font)
        self.pushButtonLogOut.setStyleSheet("QPushButton {\n"
"    background-color: #F6D2B6;\n"
"    color: #7A3E12;\n"
"    border-radius: 10px;\n"
"    font-weight: 600;\n"
"    padding: 8px 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F0BE9A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6A97D;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogOut.setIcon(icon5)
        self.pushButtonLogOut.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setGeometry(QtCore.QRect(200, 30, 1021, 681))
        self.widget_2.setStyleSheet("background-color:#F5EEE6;\n"
"border-right: 1px solid #E0C2A8;")
        self.widget_2.setObjectName("widget_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_4.setGeometry(QtCore.QRect(40, 240, 221, 291))
        self.frame_4.setStyleSheet("background-color: #FFF6ED;\n"
"border-radius: 18px;\n"
"border: 1px solid #E6C8A8;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_10.setStyleSheet("color: #7A4A1E;\n"
"font-size: 16px;\n"
"font-weight: 600;\n"
"border: none;\n"
"background: transparent;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_14.setStyleSheet("color: #A07C55;\n"
"font-size: 11px;\n"
"border: none;\n"
"background: transparent;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/dashboard.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.frame_7 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_7.setGeometry(QtCore.QRect(510, 240, 221, 291))
        self.frame_7.setStyleSheet("background-color: #FFF6ED;\n"
"border-radius: 18px;\n"
"border: 1px solid #E6C8A8;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_13.setStyleSheet("color: #7A4A1E;\n"
"font-size: 16px;\n"
"font-weight: 600;\n"
"border: none;\n"
"background: transparent;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_17 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_17.setStyleSheet("color: #A07C55;\n"
"font-size: 11px;\n"
"border: none;\n"
"background: transparent;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/schedule.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.frame_8 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_8.setGeometry(QtCore.QRect(750, 240, 211, 281))
        self.frame_8.setStyleSheet("background-color: #FFF6ED;\n"
"border-radius: 18px;\n"
"border: 1px solid #E6C8A8;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_20.setStyleSheet("color: #7A4A1E;\n"
"font-size: 16px;\n"
"font-weight: 600;\n"
"border: none;\n"
"background: transparent;")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_21.setStyleSheet("color: #A07C55;\n"
"font-size: 11px;\n"
"border: none;\n"
"background: transparent;")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/content-creation.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(350, 70, 340, 81))
        self.label_2.setStyleSheet("color: #7A4A1E;\n"
"font-size: 16px;\n"
"font-weight: 600;\n"
"border: none;\n"
"background: transparent;")
        self.label_2.setObjectName("label_2")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(260, 130, 520, 41))
        self.label_16.setStyleSheet("color: #A07C55;\n"
"font-size: 11px;\n"
"border: none;\n"
"background: transparent;")
        self.label_16.setObjectName("label_16")
        self.frame_5 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_5.setGeometry(QtCore.QRect(280, 240, 211, 291))
        self.frame_5.setStyleSheet("background-color: #FFF6ED;\n"
"border-radius: 18px;\n"
"border: 1px solid #E6C8A8;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_11.setStyleSheet("color: #7A4A1E;\n"
"font-size: 16px;\n"
"font-weight: 600;\n"
"border: none;\n"
"background: transparent;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_15.setStyleSheet("color: #A07C55;\n"
"font-size: 11px;\n"
"border: none;\n"
"background: transparent;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/customer.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.headerWidget = QtWidgets.QFrame(parent=Form)
        self.headerWidget.setGeometry(QtCore.QRect(-1, 0, 1211, 51))
        self.headerWidget.setStyleSheet("#headerWidget{\n"
"background-color:#C89B6D;\n"
"border:none;\n"
"}")
        self.headerWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.headerWidget.setObjectName("headerWidget")
        self.label = QtWidgets.QLabel(parent=self.headerWidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 131, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\Elearning\\Lumora_Studio_Booking_System\\Lumora_Studio_Booking_System\\admin_ui\\home_admin\\ui\\../images/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_19 = QtWidgets.QLabel(parent=self.headerWidget)
        self.label_19.setGeometry(QtCore.QRect(110, 0, 311, 51))
        self.label_19.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:18pt;\n"
"font-weight:bold;\n"
"border:none;")
        self.label_19.setObjectName("label_19")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonDashBoard.setText(_translate("Form", "DashBoard"))
        self.pushButtonAppointments.setText(_translate("Form", "Appointments"))
        self.pushButtonCustomers.setText(_translate("Form", "Customers"))
        self.pushButtonGallery.setText(_translate("Form", "Content"))
        self.pushButton_8.setText(_translate("Form", "Admin Home"))
        self.pushButtonLogOut.setText(_translate("Form", "Log Out"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:700;\">Dashboard</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">System overview</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Schedule</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Manage appointments</span></p></body></html>"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Content</span></p></body></html>"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Manage gallery and <br/>system content</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt;\">Hello Admin!</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Choose funtions that you want to manage</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Customer</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Manage customer info</span></p></body></html>"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:26pt;\">Studio LUMORA</span></p></body></html>"))
