# Form implementation generated from reading ui file '/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/MainWindow1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setStyleSheet("/* ===== GLOBAL FONT ===== */\n"
"* {\n"
"    font-family: \"Playfair Display\";\n"
"}\n"
"\n"
"\n"
"\n"
"/* ===== HEADER BAR ===== */\n"
"#headerFrame {\n"
"    background-color: #B8845E;\n"
"}\n"
"\n"
"/* ===== PHONE BOX ===== */\n"
"#phoneFrame {\n"
"    background-color: #E6CBB2;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* ===== DASHBOARD TITLE ===== */\n"
"#titleLabel {\n"
"    color: #6B3F2A;\n"
"    font-size: 34px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== MAIN CONTAINER ===== */\n"
"#mainContainer {\n"
"    background-color: #F8F1E8;\n"
"    border: 2px solid #C28B5D;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* ===== TOP STAT CARDS ===== */\n"
"#cardFrame_1,\n"
"#cardFrame_2,\n"
"#cardFrame_3 {\n"
"    background-color: #F8F1E8;\n"
"    border: 2px solid #D1A37A;\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"/* ===== STAT CARD TITLES ===== */\n"
"#title_1,\n"
"#title_2,\n"
"#title_3 {\n"
"    color: #5A3220;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== BIG NUMBER ===== */\n"
"#bigNumber_1,\n"
"#bigNumber_2,\n"
"#bigNumber_3 {\n"
"    color: #5A3220;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== SMALL TEXT ===== */\n"
"#smallText_1,\n"
"#smallText_2,\n"
"#smallText_3 {\n"
"    color: #8C5B3E;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* ===== CHART FRAMES ===== */\n"
"#chartFrame_1,\n"
"#chartFrame_2 {\n"
"    background-color: #F8F1E8;\n"
"    border: 2px dashed #C28B5D;\n"
"    border-radius: 15px;\n"
"    padding: 15px;\n"
"}\n"
"\n"
"/* ===== CHART TITLE ===== */\n"
"#chartTitle_1,\n"
"#chartTitle_2 {\n"
"    color: #5A3220;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== CHART SUBTEXT ===== */\n"
"#chartSub_1,\n"
"#chartSub_2 {\n"
"    color: #8C5B3E;\n"
"    font-size: 14px;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #F5EBDD;\n"
"}\n"
"\n"
"#footerFrame {\n"
"    background-color: #A36F4B;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headerFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(0, 20, 1211, 41))
        self.headerFrame.setStyleSheet("QFrame {\n"
"    background-color: #B8845E;\n"
"}\n"
"")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 181, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/../../../../Downloads/ChatGPT Image Feb 12, 2026, 06_00_15 PM.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 181, 31))
        self.label.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 20px;\n"
"")
        self.label.setObjectName("label")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(420, 70, 261, 31))
        self.titleLabel.setObjectName("titleLabel")
        self.mainContainer = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainContainer.setGeometry(QtCore.QRect(100, 110, 931, 511))
        self.mainContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainContainer.setObjectName("mainContainer")
        self.cardFrame_1 = QtWidgets.QFrame(parent=self.mainContainer)
        self.cardFrame_1.setGeometry(QtCore.QRect(9, 9, 291, 131))
        self.cardFrame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardFrame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardFrame_1.setObjectName("cardFrame_1")
        self.title_1 = QtWidgets.QLabel(parent=self.cardFrame_1)
        self.title_1.setGeometry(QtCore.QRect(40, 10, 141, 31))
        self.title_1.setObjectName("title_1")
        self.bigNumber_1 = QtWidgets.QLabel(parent=self.cardFrame_1)
        self.bigNumber_1.setGeometry(QtCore.QRect(40, 40, 111, 41))
        self.bigNumber_1.setObjectName("bigNumber_1")
        self.smallText_1 = QtWidgets.QLabel(parent=self.cardFrame_1)
        self.smallText_1.setGeometry(QtCore.QRect(30, 80, 171, 31))
        self.smallText_1.setObjectName("smallText_1")
        self.label_3 = QtWidgets.QLabel(parent=self.cardFrame_1)
        self.label_3.setGeometry(QtCore.QRect(-30, -10, 101, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/../../../../Downloads/ChatGPT Image 03_40_48 20 thg 2, 2026.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.cardFrame_2 = QtWidgets.QFrame(parent=self.mainContainer)
        self.cardFrame_2.setGeometry(QtCore.QRect(310, 10, 301, 131))
        self.cardFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardFrame_2.setObjectName("cardFrame_2")
        self.title_2 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.title_2.setGeometry(QtCore.QRect(60, 15, 151, 21))
        self.title_2.setObjectName("title_2")
        self.bigNumber_2 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.bigNumber_2.setGeometry(QtCore.QRect(60, 50, 61, 31))
        self.bigNumber_2.setObjectName("bigNumber_2")
        self.smallText_2 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.smallText_2.setGeometry(QtCore.QRect(60, 80, 161, 21))
        self.smallText_2.setObjectName("smallText_2")
        self.label_4 = QtWidgets.QLabel(parent=self.cardFrame_2)
        self.label_4.setGeometry(QtCore.QRect(-20, -10, 101, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/../../../../Downloads/ChatGPT Image 03_45_30 20 thg 2, 2026.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.cardFrame_3 = QtWidgets.QFrame(parent=self.mainContainer)
        self.cardFrame_3.setGeometry(QtCore.QRect(620, 10, 281, 131))
        self.cardFrame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardFrame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardFrame_3.setObjectName("cardFrame_3")
        self.title_3 = QtWidgets.QLabel(parent=self.cardFrame_3)
        self.title_3.setGeometry(QtCore.QRect(50, 15, 141, 21))
        self.title_3.setObjectName("title_3")
        self.bigNumber_3 = QtWidgets.QLabel(parent=self.cardFrame_3)
        self.bigNumber_3.setGeometry(QtCore.QRect(50, 50, 61, 31))
        self.bigNumber_3.setObjectName("bigNumber_3")
        self.smallText_3 = QtWidgets.QLabel(parent=self.cardFrame_3)
        self.smallText_3.setGeometry(QtCore.QRect(40, 80, 191, 31))
        self.smallText_3.setObjectName("smallText_3")
        self.label_5 = QtWidgets.QLabel(parent=self.cardFrame_3)
        self.label_5.setGeometry(QtCore.QRect(-10, 0, 81, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/../../../../Downloads/ChatGPT Image 03_50_31 20 thg 2, 2026.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.chartFrame_1 = QtWidgets.QFrame(parent=self.mainContainer)
        self.chartFrame_1.setGeometry(QtCore.QRect(20, 150, 471, 341))
        self.chartFrame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartFrame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.chartFrame_1.setObjectName("chartFrame_1")
        self.label_12 = QtWidgets.QLabel(parent=self.chartFrame_1)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 81, 61))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/../../../../Downloads/ChatGPT Image 03_54_50 20 thg 2, 2026.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.chartTitle_1 = QtWidgets.QLabel(parent=self.chartFrame_1)
        self.chartTitle_1.setGeometry(QtCore.QRect(120, 120, 161, 21))
        self.chartTitle_1.setObjectName("chartTitle_1")
        self.chartSub_1 = QtWidgets.QLabel(parent=self.chartFrame_1)
        self.chartSub_1.setGeometry(QtCore.QRect(120, 150, 191, 16))
        self.chartSub_1.setObjectName("chartSub_1")
        self.chartFrame_2 = QtWidgets.QFrame(parent=self.mainContainer)
        self.chartFrame_2.setGeometry(QtCore.QRect(500, 150, 411, 341))
        self.chartFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.chartFrame_2.setObjectName("chartFrame_2")
        self.label_13 = QtWidgets.QLabel(parent=self.chartFrame_2)
        self.label_13.setGeometry(QtCore.QRect(-10, 0, 101, 61))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("/Users/hanhnguyen/PycharmProjects/PythonProject2/ktlt/dash/../../../../Downloads/ChatGPT Image 03_56_48 20 thg 2, 2026.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.chartTitle_2 = QtWidgets.QLabel(parent=self.chartFrame_2)
        self.chartTitle_2.setGeometry(QtCore.QRect(130, 120, 141, 21))
        self.chartTitle_2.setObjectName("chartTitle_2")
        self.chartSub_2 = QtWidgets.QLabel(parent=self.chartFrame_2)
        self.chartSub_2.setGeometry(QtCore.QRect(130, 150, 121, 16))
        self.chartSub_2.setObjectName("chartSub_2")
        self.footerFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.footerFrame.setGeometry(QtCore.QRect(0, 629, 1291, 71))
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footerFrame.setObjectName("footerFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "STUDIO LUMORA"))
        self.titleLabel.setText(_translate("MainWindow", "DASHBOARD"))
        self.title_1.setText(_translate("MainWindow", "Total Appointments"))
        self.bigNumber_1.setText(_translate("MainWindow", "000"))
        self.smallText_1.setText(_translate("MainWindow", "Total bookings"))
        self.title_2.setText(_translate("MainWindow", "Customers Today"))
        self.bigNumber_2.setText(_translate("MainWindow", "00"))
        self.smallText_2.setText(_translate("MainWindow", "Customers today"))
        self.title_3.setText(_translate("MainWindow", "Total This Week"))
        self.bigNumber_3.setText(_translate("MainWindow", "00"))
        self.smallText_3.setText(_translate("MainWindow", "Bookings this week"))
        self.chartTitle_1.setText(_translate("MainWindow", "Line Chart"))
        self.chartSub_1.setText(_translate("MainWindow", "Booking by Day"))
        self.chartTitle_2.setText(_translate("MainWindow", "Pie Chart"))
        self.chartSub_2.setText(_translate("MainWindow", "Customer Ratio"))
